$axure.loadCurrentPage({
  "url":"一手房-全部楼盘.html",
  "generationDate":new Date(1408598585988.02),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"54ae27dd8c4542728d94fb74151aee52",
    "type":"Axure:Page",
    "name":"一手房-全部楼盘",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e22c71a4d5424e6a8ed536c186280b3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":427,
              "y":124},
            "size":{
              "width":81,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4eca29f613b547f5b78841b8968921d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":427,
                  "y":124},
                "size":{
                  "width":81,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9e32f7e0cb04eeeb2476406cea3cd17",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'AvantGarde Bk BT Book', 'AvantGarde Bk BT'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":320,
              "y":115},
            "size":{
              "width":23,
              "height":34},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fd3a70c925243428f022b4f1855f4d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'AvantGarde Bk BT Book', 'AvantGarde Bk BT'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":320,
                  "y":115},
                "size":{
                  "width":23,
                  "height":34},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc6ca9432ce348e09c2b46d42c8ec351",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":11},
            "size":{
              "width":405,
              "height":776},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2fbd5bfecc34749b50ce323b75f4b89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":268,
                  "y":11},
                "size":{
                  "width":405,
                  "height":776},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信首页-一_展示区/u8.png"}},
{
          "id":"ae54cd779a8d45558149b8b3f43e2861",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":378,
              "y":124},
            "size":{
              "width":100,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a5d4514213546e8be8d3c12b74b87a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":378,
                  "y":124},
                "size":{
                  "width":100,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ce7e4fa2ee148cb9f2d34fa4c06ad7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'AvantGarde Bk BT Book', 'AvantGarde Bk BT'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":313,
              "y":115},
            "size":{
              "width":23,
              "height":34},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ef89478df32451d8f59c05c6e3c91ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'AvantGarde Bk BT Book', 'AvantGarde Bk BT'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":313,
                  "y":115},
                "size":{
                  "width":23,
                  "height":34},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页一手房",
                      "target":{
                        "targetType":"page",
                        "url":"首页一手房.html",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25116edc958d44fb949d524c5d554c73",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":307,
              "y":154},
            "size":{
              "width":323,
              "height":520}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d415cc3f5f94073bbfbcda219a5d659",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":307,
                  "y":154},
                "size":{
                  "width":323,
                  "height":520}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信首页-一_展示区/u14.png"}},
{
          "id":"77d0acd0e4994365946cbaf715c04a38",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":336,
              "y":113},
            "size":{
              "width":41,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1c4f0231b624d98876ec5aee66ca2a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":336,
                  "y":113},
                "size":{
                  "width":41,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信首页-一_展示区/u26.png"}},
{
          "id":"974c5ff19f99448cbabf76d743d02815",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":319,
              "y":195},
            "size":{
              "width":302,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"5e27a1b6fc114b789d9f1280ac9f0b25",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":326,
              "y":202},
            "size":{
              "width":47,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fb9237541a4462aa6e56a6962d51566",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":326,
                  "y":202},
                "size":{
                  "width":47,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db6a911d2584474081a9a6e4de7873dd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":306,
              "y":154},
            "size":{
              "width":327,
              "height":38},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a97b8fa2c5884bd3a3e827730077e442",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":306,
                  "y":154},
                "size":{
                  "width":327,
                  "height":38},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一手房-新盘速递/u17.png"}},
{
          "id":"4e796a95333c4b1f8093145a6f9ec888",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":444,
              "y":162},
            "size":{
              "width":173,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41440a7de89c440b9a70b35c94e3978f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":444,
                  "y":162},
                "size":{
                  "width":173,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"83c00dd6ec394606a7574306824e7c99",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":308},
            "size":{
              "width":322,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d417abbfaeb4fd5a9301524734a505a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":308,
                  "y":308},
                "size":{
                  "width":322,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一手房-新盘速递/u21.png"}},
{
          "id":"5eae209a58704fddb7dff35f52d194ee",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":315,
              "y":317},
            "size":{
              "width":111,
              "height":63},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24f816cdfd3d4f9cbd711c22d9b54970",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":315,
                  "y":317},
                "size":{
                  "width":111,
                  "height":63},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信首页-一_展示区/u32.png"}},
{
          "id":"599afb4d4bda45bfb1710afb0f3fdf5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "location":{
              "x":436,
              "y":317},
            "size":{
              "width":203,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e6d60e398fd41dc8b0276716abe0aad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "location":{
                  "x":436,
                  "y":317},
                "size":{
                  "width":203,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"609281a3435f409399954f2ac723f054",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":436,
              "y":337},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d76e219b76c480d90c590fa29bef5a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":436,
                  "y":337},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"424e3409a2104bd685b3cdb310a85aaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":436,
              "y":353},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f513818f63a84736a35c5e28b45b09d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":436,
                  "y":353},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"646817e9d76940459e22222729e0b692",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":228},
            "size":{
              "width":322,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"181a64dbe73d4e749689562121345269",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":308,
                  "y":228},
                "size":{
                  "width":322,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新房速递-详情",
                      "target":{
                        "targetType":"page",
                        "url":"新房速递-详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/一手房-新盘速递/u21.png"}},
{
          "id":"3f51080daf284f5287c46c9c0858a7fa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":313,
              "y":237},
            "size":{
              "width":111,
              "height":63},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03a0debb8d384701bfda0d468b3b948e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":313,
                  "y":237},
                "size":{
                  "width":111,
                  "height":63},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信首页-一_展示区/u32.png"}},
{
          "id":"929fb6c6954147fda9119493a5734bec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "location":{
              "x":434,
              "y":237},
            "size":{
              "width":203,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b45c913b6d6b4b49bf91c1398d532ff6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "location":{
                  "x":434,
                  "y":237},
                "size":{
                  "width":203,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1dab9bac942344868a4d73a5d35e7527",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":434,
              "y":263},
            "size":{
              "width":150,
              "height":10},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e7d1a7d7a7f4f38a8bfdc4f7c2f548f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":434,
                  "y":263},
                "size":{
                  "width":150,
                  "height":10},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f4cb0ae6783a4d0eba499e49fb74e104",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":434,
              "y":273},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10a8c7c350304434b63e7be280c25070",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":434,
                  "y":273},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0e5932506d94debaa218f1bccae9126",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta cursiva', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCC3399,
              "opacity":1},
            "location":{
              "x":554,
              "y":254},
            "size":{
              "width":76,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5fcd8c5d56d4e5ba813cb00953204c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta cursiva', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCC3399,
                  "opacity":1},
                "location":{
                  "x":554,
                  "y":254},
                "size":{
                  "width":76,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6cbc70dca4e45bca82fe8e71e14dbce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":388},
            "size":{
              "width":322,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91d2d47771ec4f21bdfb4e5979cfac4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":308,
                  "y":388},
                "size":{
                  "width":322,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一手房-新盘速递/u21.png"}},
{
          "id":"465ee413ffa748b8b02b977ed381be45",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":315,
              "y":397},
            "size":{
              "width":111,
              "height":63},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbaf64b9cc9d4754b351d8350d3eaef7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":315,
                  "y":397},
                "size":{
                  "width":111,
                  "height":63},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信首页-一_展示区/u32.png"}},
{
          "id":"a861adaa42eb409a82f3f61d2a6f9635",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "location":{
              "x":436,
              "y":397},
            "size":{
              "width":203,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9725f3310dc4eeb9d6bde7ca01002b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "location":{
                  "x":436,
                  "y":397},
                "size":{
                  "width":203,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b3e6c96895449988ed3ce9ff309818a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":436,
              "y":417},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01f34ee594e4461687b2f2423e15fcc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":436,
                  "y":417},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd428978ed874b69bbbf8bb12f7841a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":436,
              "y":433},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78416577f0374d97b8a565d9bf4d6d44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":436,
                  "y":433},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94c7009e7eea4dada72dc002aae25a60",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":468},
            "size":{
              "width":322,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4810d911b484efaa230e85963224483",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":308,
                  "y":468},
                "size":{
                  "width":322,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一手房-新盘速递/u21.png"}},
{
          "id":"157db43436ae463eb5998e332bafc312",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":315,
              "y":477},
            "size":{
              "width":111,
              "height":63},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c910059c727443f829526666fca9b79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":315,
                  "y":477},
                "size":{
                  "width":111,
                  "height":63},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信首页-一_展示区/u32.png"}},
{
          "id":"6dba302a8bc34bb88226757ba7543728",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "location":{
              "x":436,
              "y":477},
            "size":{
              "width":203,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"115873d15fed4d448641e6150634ec00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "location":{
                  "x":436,
                  "y":477},
                "size":{
                  "width":203,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ffdce50ea8f0476c85406d7d376e42f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":436,
              "y":497},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02dd86382b31447288727af8aec14e73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":436,
                  "y":497},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08b021c98ca54e188b3a05e2c416a2e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":436,
              "y":513},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b0ada4670c34b8b9633ec96c522cf48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":436,
                  "y":513},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d3c578643ca4449a54fff9ec70122a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":549},
            "size":{
              "width":322,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a71e2e9f2dfc449a803dac05d97ee1c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":308,
                  "y":549},
                "size":{
                  "width":322,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一手房-新盘速递/u21.png"}},
{
          "id":"4258b8a70fca4e459a9d336a6090da0f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":315,
              "y":558},
            "size":{
              "width":111,
              "height":63},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab1aea629ab849d89f7af2bd4bd6fe0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":315,
                  "y":558},
                "size":{
                  "width":111,
                  "height":63},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信首页-一_展示区/u32.png"}},
{
          "id":"0696cb2bd8af43c886d9efe4f01e9c2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "location":{
              "x":436,
              "y":558},
            "size":{
              "width":203,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02f81bea0fe345c097a9a064586d3b32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "location":{
                  "x":436,
                  "y":558},
                "size":{
                  "width":203,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cbc4285c31f1445fb18544baed1ff8d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":436,
              "y":578},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f248e62f71884347a6a846bcd413e3b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":436,
                  "y":578},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc2ff1138f0d4e47a7e325ba52714fd5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":436,
              "y":594},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66e4930863434060901b2b0a12958a44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":436,
                  "y":594},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a46bff0d93d640bd9e666fc5ab510423",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":412,
              "y":645},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58dbbca3839f44139c0a13b417ba65a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":412,
                  "y":645},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b09e14952ed04a83b8980ec66c537841",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":373,
              "y":202},
            "size":{
              "width":32,
              "height":16},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59a2722bce384af190d34139e7e633a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":373,
                  "y":202},
                "size":{
                  "width":32,
                  "height":16},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新房速递-区域",
                      "target":{
                        "targetType":"page",
                        "url":"新房速递-区域.html",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/一手房-新盘速递/u67.png"}},
{
          "id":"47f60d57a59b425583589da46a8c580c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta cursiva', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCC3399,
              "opacity":1},
            "location":{
              "x":552,
              "y":333},
            "size":{
              "width":76,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c07d28031df747eda3db5e82fd9a7d97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta cursiva', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCC3399,
                  "opacity":1},
                "location":{
                  "x":552,
                  "y":333},
                "size":{
                  "width":76,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af53b83e152b4a5da6e89d8b4f9a9af2",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":416,
              "y":197},
            "size":{
              "width":10,
              "height":28}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/一手房-新盘速递/u71_line.png"}},
{
          "id":"bcde7684287b4463bbae187aa5b4c46d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":426,
              "y":202},
            "size":{
              "width":47,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a90b95fdc91447b8cd1605eca2621b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":426,
                  "y":202},
                "size":{
                  "width":47,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6aab5706fe84a008e92fa9d8e3619da",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":521,
              "y":192},
            "size":{
              "width":10,
              "height":33}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/一手房-新盘速递/u74_line.png"}},
{
          "id":"c31bbbd860f642bfb1c57220f24a799f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":201},
            "size":{
              "width":47,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9efb44c8325d42cca5166da73a0c5d09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":201},
                "size":{
                  "width":47,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3745a093ee324521bbc64721441e0fb2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":593,
              "y":201},
            "size":{
              "width":15,
              "height":16},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6fdcd0df78048ea9a86712518996abd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":593,
                  "y":201},
                "size":{
                  "width":15,
                  "height":16},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一手房-新盘速递/u67.png"}},
{
          "id":"2f4ffcba10794ee0a99c9174beb6d55b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":496,
              "y":201},
            "size":{
              "width":15,
              "height":16},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05af14aaf7884693b4319a6e3ea5de9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":496,
                  "y":201},
                "size":{
                  "width":15,
                  "height":16},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一手房-新盘速递/u67.png"}},
{
          "id":"dc6d7c8bbc0c45b1bae4492ef126a956",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta cursiva', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCC3399,
              "opacity":1},
            "location":{
              "x":554,
              "y":414},
            "size":{
              "width":76,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63464a10de2c40caae6cb7356bffeada",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta cursiva', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCC3399,
                  "opacity":1},
                "location":{
                  "x":554,
                  "y":414},
                "size":{
                  "width":76,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"477594fa266b4aac85aabf0a8d2e8b33",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta cursiva', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCC3399,
              "opacity":1},
            "location":{
              "x":554,
              "y":494},
            "size":{
              "width":76,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79880753ff4a45c2af57adbadef9924a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta cursiva', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCC3399,
                  "opacity":1},
                "location":{
                  "x":554,
                  "y":494},
                "size":{
                  "width":76,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2eedd8e3417949438baaf9ef3ad42e66",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta cursiva', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCC3399,
              "opacity":1},
            "location":{
              "x":554,
              "y":575},
            "size":{
              "width":76,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1925ebf385ef44f58d0b6f880dff0180",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta cursiva', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCC3399,
                  "opacity":1},
                "location":{
                  "x":554,
                  "y":575},
                "size":{
                  "width":76,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e22c71a4d5424e6a8ed536c186280b3e":{
      "scriptId":"u0"},
    "4eca29f613b547f5b78841b8968921d5":{
      "scriptId":"u1"},
    "c9e32f7e0cb04eeeb2476406cea3cd17":{
      "scriptId":"u2"},
    "8fd3a70c925243428f022b4f1855f4d0":{
      "scriptId":"u3"},
    "cc6ca9432ce348e09c2b46d42c8ec351":{
      "scriptId":"u4"},
    "a2fbd5bfecc34749b50ce323b75f4b89":{
      "scriptId":"u5"},
    "ae54cd779a8d45558149b8b3f43e2861":{
      "scriptId":"u6"},
    "1a5d4514213546e8be8d3c12b74b87a3":{
      "scriptId":"u7"},
    "5ce7e4fa2ee148cb9f2d34fa4c06ad7d":{
      "scriptId":"u8"},
    "2ef89478df32451d8f59c05c6e3c91ae":{
      "scriptId":"u9"},
    "25116edc958d44fb949d524c5d554c73":{
      "scriptId":"u10"},
    "6d415cc3f5f94073bbfbcda219a5d659":{
      "scriptId":"u11"},
    "77d0acd0e4994365946cbaf715c04a38":{
      "scriptId":"u12"},
    "a1c4f0231b624d98876ec5aee66ca2a3":{
      "scriptId":"u13"},
    "974c5ff19f99448cbabf76d743d02815":{
      "scriptId":"u14"},
    "5e27a1b6fc114b789d9f1280ac9f0b25":{
      "scriptId":"u15"},
    "0fb9237541a4462aa6e56a6962d51566":{
      "scriptId":"u16"},
    "db6a911d2584474081a9a6e4de7873dd":{
      "scriptId":"u17"},
    "a97b8fa2c5884bd3a3e827730077e442":{
      "scriptId":"u18"},
    "4e796a95333c4b1f8093145a6f9ec888":{
      "scriptId":"u19"},
    "41440a7de89c440b9a70b35c94e3978f":{
      "scriptId":"u20"},
    "83c00dd6ec394606a7574306824e7c99":{
      "scriptId":"u21"},
    "0d417abbfaeb4fd5a9301524734a505a":{
      "scriptId":"u22"},
    "5eae209a58704fddb7dff35f52d194ee":{
      "scriptId":"u23"},
    "24f816cdfd3d4f9cbd711c22d9b54970":{
      "scriptId":"u24"},
    "599afb4d4bda45bfb1710afb0f3fdf5c":{
      "scriptId":"u25"},
    "5e6d60e398fd41dc8b0276716abe0aad":{
      "scriptId":"u26"},
    "609281a3435f409399954f2ac723f054":{
      "scriptId":"u27"},
    "3d76e219b76c480d90c590fa29bef5a6":{
      "scriptId":"u28"},
    "424e3409a2104bd685b3cdb310a85aaa":{
      "scriptId":"u29"},
    "f513818f63a84736a35c5e28b45b09d1":{
      "scriptId":"u30"},
    "646817e9d76940459e22222729e0b692":{
      "scriptId":"u31"},
    "181a64dbe73d4e749689562121345269":{
      "scriptId":"u32"},
    "3f51080daf284f5287c46c9c0858a7fa":{
      "scriptId":"u33"},
    "03a0debb8d384701bfda0d468b3b948e":{
      "scriptId":"u34"},
    "929fb6c6954147fda9119493a5734bec":{
      "scriptId":"u35"},
    "b45c913b6d6b4b49bf91c1398d532ff6":{
      "scriptId":"u36"},
    "1dab9bac942344868a4d73a5d35e7527":{
      "scriptId":"u37"},
    "7e7d1a7d7a7f4f38a8bfdc4f7c2f548f":{
      "scriptId":"u38"},
    "f4cb0ae6783a4d0eba499e49fb74e104":{
      "scriptId":"u39"},
    "10a8c7c350304434b63e7be280c25070":{
      "scriptId":"u40"},
    "c0e5932506d94debaa218f1bccae9126":{
      "scriptId":"u41"},
    "d5fcd8c5d56d4e5ba813cb00953204c7":{
      "scriptId":"u42"},
    "c6cbc70dca4e45bca82fe8e71e14dbce":{
      "scriptId":"u43"},
    "91d2d47771ec4f21bdfb4e5979cfac4d":{
      "scriptId":"u44"},
    "465ee413ffa748b8b02b977ed381be45":{
      "scriptId":"u45"},
    "cbaf64b9cc9d4754b351d8350d3eaef7":{
      "scriptId":"u46"},
    "a861adaa42eb409a82f3f61d2a6f9635":{
      "scriptId":"u47"},
    "f9725f3310dc4eeb9d6bde7ca01002b4":{
      "scriptId":"u48"},
    "1b3e6c96895449988ed3ce9ff309818a":{
      "scriptId":"u49"},
    "01f34ee594e4461687b2f2423e15fcc6":{
      "scriptId":"u50"},
    "dd428978ed874b69bbbf8bb12f7841a4":{
      "scriptId":"u51"},
    "78416577f0374d97b8a565d9bf4d6d44":{
      "scriptId":"u52"},
    "94c7009e7eea4dada72dc002aae25a60":{
      "scriptId":"u53"},
    "d4810d911b484efaa230e85963224483":{
      "scriptId":"u54"},
    "157db43436ae463eb5998e332bafc312":{
      "scriptId":"u55"},
    "1c910059c727443f829526666fca9b79":{
      "scriptId":"u56"},
    "6dba302a8bc34bb88226757ba7543728":{
      "scriptId":"u57"},
    "115873d15fed4d448641e6150634ec00":{
      "scriptId":"u58"},
    "ffdce50ea8f0476c85406d7d376e42f3":{
      "scriptId":"u59"},
    "02dd86382b31447288727af8aec14e73":{
      "scriptId":"u60"},
    "08b021c98ca54e188b3a05e2c416a2e4":{
      "scriptId":"u61"},
    "0b0ada4670c34b8b9633ec96c522cf48":{
      "scriptId":"u62"},
    "2d3c578643ca4449a54fff9ec70122a1":{
      "scriptId":"u63"},
    "a71e2e9f2dfc449a803dac05d97ee1c0":{
      "scriptId":"u64"},
    "4258b8a70fca4e459a9d336a6090da0f":{
      "scriptId":"u65"},
    "ab1aea629ab849d89f7af2bd4bd6fe0a":{
      "scriptId":"u66"},
    "0696cb2bd8af43c886d9efe4f01e9c2b":{
      "scriptId":"u67"},
    "02f81bea0fe345c097a9a064586d3b32":{
      "scriptId":"u68"},
    "cbc4285c31f1445fb18544baed1ff8d7":{
      "scriptId":"u69"},
    "f248e62f71884347a6a846bcd413e3b6":{
      "scriptId":"u70"},
    "bc2ff1138f0d4e47a7e325ba52714fd5":{
      "scriptId":"u71"},
    "66e4930863434060901b2b0a12958a44":{
      "scriptId":"u72"},
    "a46bff0d93d640bd9e666fc5ab510423":{
      "scriptId":"u73"},
    "58dbbca3839f44139c0a13b417ba65a3":{
      "scriptId":"u74"},
    "b09e14952ed04a83b8980ec66c537841":{
      "scriptId":"u75"},
    "59a2722bce384af190d34139e7e633a2":{
      "scriptId":"u76"},
    "47f60d57a59b425583589da46a8c580c":{
      "scriptId":"u77"},
    "c07d28031df747eda3db5e82fd9a7d97":{
      "scriptId":"u78"},
    "af53b83e152b4a5da6e89d8b4f9a9af2":{
      "scriptId":"u79"},
    "bcde7684287b4463bbae187aa5b4c46d":{
      "scriptId":"u80"},
    "5a90b95fdc91447b8cd1605eca2621b1":{
      "scriptId":"u81"},
    "c6aab5706fe84a008e92fa9d8e3619da":{
      "scriptId":"u82"},
    "c31bbbd860f642bfb1c57220f24a799f":{
      "scriptId":"u83"},
    "9efb44c8325d42cca5166da73a0c5d09":{
      "scriptId":"u84"},
    "3745a093ee324521bbc64721441e0fb2":{
      "scriptId":"u85"},
    "a6fdcd0df78048ea9a86712518996abd":{
      "scriptId":"u86"},
    "2f4ffcba10794ee0a99c9174beb6d55b":{
      "scriptId":"u87"},
    "05af14aaf7884693b4319a6e3ea5de9f":{
      "scriptId":"u88"},
    "dc6d7c8bbc0c45b1bae4492ef126a956":{
      "scriptId":"u89"},
    "63464a10de2c40caae6cb7356bffeada":{
      "scriptId":"u90"},
    "477594fa266b4aac85aabf0a8d2e8b33":{
      "scriptId":"u91"},
    "79880753ff4a45c2af57adbadef9924a":{
      "scriptId":"u92"},
    "2eedd8e3417949438baaf9ef3ad42e66":{
      "scriptId":"u93"},
    "1925ebf385ef44f58d0b6f880dff0180":{
      "scriptId":"u94"}}});