$axure.loadCurrentPage({
  "url":"楼盘信息-详情_1.html",
  "generationDate":new Date(1408598589332.27),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b609ed769d594950a06caac670c98374",
    "type":"Axure:Page",
    "name":"楼盘信息-详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ae0cff66057d4fa3b91712d1c9de99b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":427,
              "y":124},
            "size":{
              "width":81,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"caf34220d4d84e3185417a64c1999f3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":427,
                  "y":124},
                "size":{
                  "width":81,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c9bdfe960d6464fa9653e0599972425",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'AvantGarde Bk BT Book', 'AvantGarde Bk BT'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":320,
              "y":115},
            "size":{
              "width":23,
              "height":34},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ed41758d7af404db7c5d61abe91f62a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'AvantGarde Bk BT Book', 'AvantGarde Bk BT'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":320,
                  "y":115},
                "size":{
                  "width":23,
                  "height":34},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"640033867d1e4dc09e0d6a7342d03555",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":12},
            "size":{
              "width":405,
              "height":776},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d3a6282a162479eb885015fabe53cee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":268,
                  "y":12},
                "size":{
                  "width":405,
                  "height":776},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信首页-一_展示区/u8.png"}},
{
          "id":"b8470254e7b14ab1a6304ca98a74215d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":378,
              "y":124},
            "size":{
              "width":238,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdcb189dda3f4f62943a3c5ca587b2eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":378,
                  "y":124},
                "size":{
                  "width":238,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35f565b2b4f54e2aa1d58d2c7c3109d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'AvantGarde Bk BT Book', 'AvantGarde Bk BT'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":313,
              "y":115},
            "size":{
              "width":23,
              "height":34},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d28d54d2e244265ac7b8430dd72cc5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'AvantGarde Bk BT Book', 'AvantGarde Bk BT'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":313,
                  "y":115},
                "size":{
                  "width":23,
                  "height":34},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 一手房-新盘速递",
                      "target":{
                        "targetType":"page",
                        "url":"一手房-新盘速递.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f0171c1c0624483b5a309a104d6d480",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":306,
              "y":155},
            "size":{
              "width":323,
              "height":520}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bd266541fc948b9ac81a158daa78166",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":306,
                  "y":155},
                "size":{
                  "width":323,
                  "height":520}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信首页-一_展示区/u14.png"}},
{
          "id":"9f3e20fb071c4c1db32e5d3949ff83a6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":336,
              "y":113},
            "size":{
              "width":41,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25419f4a992a448182c0da5176284475",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":336,
                  "y":113},
                "size":{
                  "width":41,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信首页-一_展示区/u26.png"}},
{
          "id":"1c2d37c4336645e28c458220f6254bcf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":306,
              "y":154},
            "size":{
              "width":327,
              "height":38},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c719f0174055494ab3eeb0db36892ec2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":306,
                  "y":154},
                "size":{
                  "width":327,
                  "height":38},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一手房-新盘速递/u17.png"}},
{
          "id":"0a38ff602df749b58f30f5ec0f5e469e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":429,
              "y":162},
            "size":{
              "width":296,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce2e50da00c44485a568be8908b2d7fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":429,
                  "y":162},
                "size":{
                  "width":296,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"09a40988d7514368a34e224a25cab889",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":299},
            "size":{
              "width":322,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b806d0573dea4c60977fd315567b73d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":308,
                  "y":299},
                "size":{
                  "width":322,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/楼盘信息-详情/u18.png"}},
{
          "id":"78c76fff6a644713b00848f0a2460c95",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":412,
              "y":645},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb51777e2d8343b5b30fbc18539b81d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":412,
                  "y":645},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cdf1f98a7e514a3b9e6d39f314f3df39",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC99},
            "location":{
              "x":306,
              "y":642},
            "size":{
              "width":83,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fde10329d83148a4adcd0804a4f0902d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC99},
                "location":{
                  "x":306,
                  "y":642},
                "size":{
                  "width":83,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/楼盘信息-详情/u22.png"}},
{
          "id":"bca716644d6e4532bbca96e8292a90d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":306,
              "y":350},
            "size":{
              "width":322,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0f514e0c2fe46c0bae13c9931a88d11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":306,
                  "y":350},
                "size":{
                  "width":322,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/楼盘信息-详情/u24.png"}},
{
          "id":"028de5a4061c4479a546ac6a28392054",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":307,
              "y":443},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"209f60025b3c48abbc518a285d5f119b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":307,
                  "y":443},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"448bf138d3ee46a6859d1d16e01a12e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":494,
              "y":445},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"282ab94ddc5d4841aeb60915027c577e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":494,
                  "y":445},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95ef86573b0540c4ae9fd666221c828e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCFF99},
            "location":{
              "x":389,
              "y":642},
            "size":{
              "width":79,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50af414ce66747b6996cc43ff4e9a400",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCFF99},
                "location":{
                  "x":389,
                  "y":642},
                "size":{
                  "width":79,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/楼盘信息-详情/u30.png"}},
{
          "id":"26e77d2809c34bc9b68c8cf9c050bb55",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF006699},
            "location":{
              "x":467,
              "y":641},
            "size":{
              "width":90,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c19b7993b7ce4dd6bb745f9b8fd0fd48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF006699},
                "location":{
                  "x":467,
                  "y":641},
                "size":{
                  "width":90,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/楼盘信息-详情/u32.png"}},
{
          "id":"35a212f86a6741a790b046c19593d749",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":308,
              "y":312},
            "size":{
              "width":202,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d4a6b887dcf4adc94e0976e1188f6ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":308,
                  "y":312},
                "size":{
                  "width":202,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3380367d71349ff9a7d827265ce4dc4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":353},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51498828a53e4064b47f94b08605db22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":308,
                  "y":353},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a36db632d7044148868ccfeeeb1b4585",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":412},
            "size":{
              "width":176,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b460db947c64912903aa711ae233e6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":308,
                  "y":412},
                "size":{
                  "width":176,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c66f79941394d36a9bade4fa5bba1e4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":305,
              "y":642},
            "size":{
              "width":324,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新房速递-详情/u62_line.png"}},
{
          "id":"446787df5b0649209c939ac8c42fb5ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":494,
              "y":416},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf8f578e30e24f16b9d1bbfa866b3084",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":494,
                  "y":416},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5ef1a470c864e30a49ea211113d419a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC99},
            "location":{
              "x":558,
              "y":642},
            "size":{
              "width":75,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8db74b5132b24a6fb9979fe506b41d0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC99},
                "location":{
                  "x":558,
                  "y":642},
                "size":{
                  "width":75,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/楼盘信息-详情/u43.png"}},
{
          "id":"4998774f7df3495e873ad77b53cf7c9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":494,
              "y":471},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b56f11c14534addb9dfa60fa4686f70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":494,
                  "y":471},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff2922abf9144f779978cc1c0a920460",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":314,
              "y":618},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9222f79f14124f03b998bb6ce883928a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":314,
                  "y":618},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b951cb0a4af14141bc701020214945a2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":606},
            "size":{
              "width":318,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/楼盘信息-详情/u53_line.png"}},
{
          "id":"3b8f6744c6d4440bbdc1052de7364747",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":407,
              "y":305},
            "size":{
              "width":10,
              "height":45}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/楼盘信息-详情/u54_line.png"}},
{
          "id":"562ae457289b4d099f6b1ebf2134f67f",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":501,
              "y":271},
            "size":{
              "width":10,
              "height":24}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/楼盘信息-详情/u55_line.png"}},
{
          "id":"dacc7fbe1e9a4193b4cab01ddf02d6f3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":229},
            "size":{
              "width":318,
              "height":80},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45c8b61aff224ce3a1fb73f427289afa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":308,
                  "y":229},
                "size":{
                  "width":318,
                  "height":80},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信首页-一_展示区/u32.png"}},
{
          "id":"038fddb516fc4453847c27e2dbe86085",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta cursiva', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0033FF,
              "opacity":1},
            "location":{
              "x":308,
              "y":192},
            "size":{
              "width":325,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b91606c1bc740e188d3f9ab91b772e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta cursiva', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1},
                "location":{
                  "x":308,
                  "y":192},
                "size":{
                  "width":325,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"83125b18069c43408bdf1ca3d4050789",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":258},
            "size":{
              "width":39,
              "height":31},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2832ceb34754bf08b9cbf9cfb2b9044",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":258},
                "size":{
                  "width":39,
                  "height":31},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新房速递-详情/u60.png"}},
{
          "id":"f0e55f57f3894fa7a97c450b77bb2c4a",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":517,
              "y":307},
            "size":{
              "width":10,
              "height":39}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/楼盘信息-详情/u62_line.png"}},
{
          "id":"5a1b45111cb9474592699c777a7d76dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":525,
              "y":322},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"288a81c39ee548049b38575f370dc3ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":525,
                  "y":322},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ca4110f8c094e688eca75c47092d7ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":419,
              "y":322},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f34e6f370c3e4bdaaa2d15e045d40517",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":419,
                  "y":322},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb76c71cc3f34259a9ee32bbcab1e087",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":308,
              "y":321},
            "size":{
              "width":160,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dcebaf33c774022884f0de798793c0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":308,
                  "y":321},
                "size":{
                  "width":160,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12ea2850e58b48ba95e301666ae8c05a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":306,
              "y":385},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3595558ebc8141bdb42b808eeba27946",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":306,
                  "y":385},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c53cd9f8ab14a5fa9563eef281427f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":471},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5a4e9e0010e489eb9c1b23cb9511b9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":308,
                  "y":471},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c34b48fa146145f5aab49f3fda41e853",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":615,
              "y":614},
            "size":{
              "width":12,
              "height":24},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d982f10b426b4df28dae2f362e95749f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":615,
                  "y":614},
                "size":{
                  "width":12,
                  "height":24},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新房速递-详情/u63.png"}},
{
          "id":"b9788f96628145d7b13063b5555001e1",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":305,
              "y":540},
            "size":{
              "width":10,
              "height":68}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/楼盘信息-详情/u75_line.png"}},
{
          "id":"7960c8b22c8a406baf8f70f3dea840d7",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":619,
              "y":543},
            "size":{
              "width":10,
              "height":68}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/楼盘信息-详情/u75_line.png"}},
{
          "id":"576b165f65694b67abf90173442f5f3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":409,
              "y":560},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f644f340e174b8ca89ae02f6e852497",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":409,
                  "y":560},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b1756c20c45a4ab7bf4448cc2b982aa8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":494,
              "y":384},
            "size":{
              "width":69,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc08112d771348bf80af73fdeb1d9c9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":494,
                  "y":384},
                "size":{
                  "width":69,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "ae0cff66057d4fa3b91712d1c9de99b6":{
      "scriptId":"u0"},
    "caf34220d4d84e3185417a64c1999f3b":{
      "scriptId":"u1"},
    "8c9bdfe960d6464fa9653e0599972425":{
      "scriptId":"u2"},
    "1ed41758d7af404db7c5d61abe91f62a":{
      "scriptId":"u3"},
    "640033867d1e4dc09e0d6a7342d03555":{
      "scriptId":"u4"},
    "2d3a6282a162479eb885015fabe53cee":{
      "scriptId":"u5"},
    "b8470254e7b14ab1a6304ca98a74215d":{
      "scriptId":"u6"},
    "bdcb189dda3f4f62943a3c5ca587b2eb":{
      "scriptId":"u7"},
    "35f565b2b4f54e2aa1d58d2c7c3109d3":{
      "scriptId":"u8"},
    "4d28d54d2e244265ac7b8430dd72cc5e":{
      "scriptId":"u9"},
    "7f0171c1c0624483b5a309a104d6d480":{
      "scriptId":"u10"},
    "4bd266541fc948b9ac81a158daa78166":{
      "scriptId":"u11"},
    "9f3e20fb071c4c1db32e5d3949ff83a6":{
      "scriptId":"u12"},
    "25419f4a992a448182c0da5176284475":{
      "scriptId":"u13"},
    "1c2d37c4336645e28c458220f6254bcf":{
      "scriptId":"u14"},
    "c719f0174055494ab3eeb0db36892ec2":{
      "scriptId":"u15"},
    "0a38ff602df749b58f30f5ec0f5e469e":{
      "scriptId":"u16"},
    "ce2e50da00c44485a568be8908b2d7fc":{
      "scriptId":"u17"},
    "09a40988d7514368a34e224a25cab889":{
      "scriptId":"u18"},
    "b806d0573dea4c60977fd315567b73d7":{
      "scriptId":"u19"},
    "78c76fff6a644713b00848f0a2460c95":{
      "scriptId":"u20"},
    "cb51777e2d8343b5b30fbc18539b81d2":{
      "scriptId":"u21"},
    "cdf1f98a7e514a3b9e6d39f314f3df39":{
      "scriptId":"u22"},
    "fde10329d83148a4adcd0804a4f0902d":{
      "scriptId":"u23"},
    "bca716644d6e4532bbca96e8292a90d5":{
      "scriptId":"u24"},
    "c0f514e0c2fe46c0bae13c9931a88d11":{
      "scriptId":"u25"},
    "028de5a4061c4479a546ac6a28392054":{
      "scriptId":"u26"},
    "209f60025b3c48abbc518a285d5f119b":{
      "scriptId":"u27"},
    "448bf138d3ee46a6859d1d16e01a12e2":{
      "scriptId":"u28"},
    "282ab94ddc5d4841aeb60915027c577e":{
      "scriptId":"u29"},
    "95ef86573b0540c4ae9fd666221c828e":{
      "scriptId":"u30"},
    "50af414ce66747b6996cc43ff4e9a400":{
      "scriptId":"u31"},
    "26e77d2809c34bc9b68c8cf9c050bb55":{
      "scriptId":"u32"},
    "c19b7993b7ce4dd6bb745f9b8fd0fd48":{
      "scriptId":"u33"},
    "35a212f86a6741a790b046c19593d749":{
      "scriptId":"u34"},
    "0d4a6b887dcf4adc94e0976e1188f6ea":{
      "scriptId":"u35"},
    "a3380367d71349ff9a7d827265ce4dc4":{
      "scriptId":"u36"},
    "51498828a53e4064b47f94b08605db22":{
      "scriptId":"u37"},
    "a36db632d7044148868ccfeeeb1b4585":{
      "scriptId":"u38"},
    "4b460db947c64912903aa711ae233e6d":{
      "scriptId":"u39"},
    "6c66f79941394d36a9bade4fa5bba1e4":{
      "scriptId":"u40"},
    "446787df5b0649209c939ac8c42fb5ad":{
      "scriptId":"u41"},
    "cf8f578e30e24f16b9d1bbfa866b3084":{
      "scriptId":"u42"},
    "a5ef1a470c864e30a49ea211113d419a":{
      "scriptId":"u43"},
    "8db74b5132b24a6fb9979fe506b41d0f":{
      "scriptId":"u44"},
    "4998774f7df3495e873ad77b53cf7c9c":{
      "scriptId":"u45"},
    "4b56f11c14534addb9dfa60fa4686f70":{
      "scriptId":"u46"},
    "ff2922abf9144f779978cc1c0a920460":{
      "scriptId":"u47"},
    "9222f79f14124f03b998bb6ce883928a":{
      "scriptId":"u48"},
    "b951cb0a4af14141bc701020214945a2":{
      "scriptId":"u49"},
    "3b8f6744c6d4440bbdc1052de7364747":{
      "scriptId":"u50"},
    "562ae457289b4d099f6b1ebf2134f67f":{
      "scriptId":"u51"},
    "dacc7fbe1e9a4193b4cab01ddf02d6f3":{
      "scriptId":"u52"},
    "45c8b61aff224ce3a1fb73f427289afa":{
      "scriptId":"u53"},
    "038fddb516fc4453847c27e2dbe86085":{
      "scriptId":"u54"},
    "0b91606c1bc740e188d3f9ab91b772e3":{
      "scriptId":"u55"},
    "83125b18069c43408bdf1ca3d4050789":{
      "scriptId":"u56"},
    "c2832ceb34754bf08b9cbf9cfb2b9044":{
      "scriptId":"u57"},
    "f0e55f57f3894fa7a97c450b77bb2c4a":{
      "scriptId":"u58"},
    "5a1b45111cb9474592699c777a7d76dc":{
      "scriptId":"u59"},
    "288a81c39ee548049b38575f370dc3ef":{
      "scriptId":"u60"},
    "7ca4110f8c094e688eca75c47092d7ff":{
      "scriptId":"u61"},
    "f34e6f370c3e4bdaaa2d15e045d40517":{
      "scriptId":"u62"},
    "eb76c71cc3f34259a9ee32bbcab1e087":{
      "scriptId":"u63"},
    "4dcebaf33c774022884f0de798793c0d":{
      "scriptId":"u64"},
    "12ea2850e58b48ba95e301666ae8c05a":{
      "scriptId":"u65"},
    "3595558ebc8141bdb42b808eeba27946":{
      "scriptId":"u66"},
    "4c53cd9f8ab14a5fa9563eef281427f9":{
      "scriptId":"u67"},
    "e5a4e9e0010e489eb9c1b23cb9511b9e":{
      "scriptId":"u68"},
    "c34b48fa146145f5aab49f3fda41e853":{
      "scriptId":"u69"},
    "d982f10b426b4df28dae2f362e95749f":{
      "scriptId":"u70"},
    "b9788f96628145d7b13063b5555001e1":{
      "scriptId":"u71"},
    "7960c8b22c8a406baf8f70f3dea840d7":{
      "scriptId":"u72"},
    "576b165f65694b67abf90173442f5f3f":{
      "scriptId":"u73"},
    "7f644f340e174b8ca89ae02f6e852497":{
      "scriptId":"u74"},
    "b1756c20c45a4ab7bf4448cc2b982aa8":{
      "scriptId":"u75"},
    "bc08112d771348bf80af73fdeb1d9c9b":{
      "scriptId":"u76"}}});