$axure.loadCurrentPage({
  "url":"新房速递-详情.html",
  "generationDate":new Date(1408598585390.98),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f10aef0f86264b35a63bb3c5c0c5d022",
    "type":"Axure:Page",
    "name":"新房速递-详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ebf0cfdbdb9644708182e1c3796e8acf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":427,
              "y":124},
            "size":{
              "width":81,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d659321250284dc2b79da5202c161647",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":427,
                  "y":124},
                "size":{
                  "width":81,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d2dce6eae0a4ec7920a6c9a3a0ab5ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'AvantGarde Bk BT Book', 'AvantGarde Bk BT'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":320,
              "y":115},
            "size":{
              "width":23,
              "height":34},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c5469ca0de14c0e8a219b9414c31d93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'AvantGarde Bk BT Book', 'AvantGarde Bk BT'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":320,
                  "y":115},
                "size":{
                  "width":23,
                  "height":34},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4bbf9d025bf44e11a1809ec1b8eba61f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":11},
            "size":{
              "width":405,
              "height":776},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e12d31197c54102ae97eb065ae19da4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":268,
                  "y":11},
                "size":{
                  "width":405,
                  "height":776},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信首页-一_展示区/u8.png"}},
{
          "id":"b5deea1e2fa443bd836528f42925acaf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":378,
              "y":124},
            "size":{
              "width":238,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd5c7418db664b91a0cff91deb759d4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":378,
                  "y":124},
                "size":{
                  "width":238,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f678210757a40e9ac30d38684b8791e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'AvantGarde Bk BT Book', 'AvantGarde Bk BT'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":313,
              "y":115},
            "size":{
              "width":23,
              "height":34},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d15073682724722a17683d3161ad825",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'AvantGarde Bk BT Book', 'AvantGarde Bk BT'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":313,
                  "y":115},
                "size":{
                  "width":23,
                  "height":34},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 一手房-新盘速递",
                      "target":{
                        "targetType":"page",
                        "url":"一手房-新盘速递.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3adc064d71104b2397070efd8992bb17",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":307,
              "y":154},
            "size":{
              "width":323,
              "height":520}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c52e6bd285e4d8680e1c022cd589e6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":307,
                  "y":154},
                "size":{
                  "width":323,
                  "height":520}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信首页-一_展示区/u14.png"}},
{
          "id":"c8dfe850d8f94c55ac256c8c77bd470d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":336,
              "y":113},
            "size":{
              "width":41,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"109fe0e630354a73a7d7e8e88b2dd3fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":336,
                  "y":113},
                "size":{
                  "width":41,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信首页-一_展示区/u26.png"}},
{
          "id":"9b8413ed89294754bf1016c786511823",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":306,
              "y":154},
            "size":{
              "width":327,
              "height":38},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31bed65ff0f249c490e7234ea03c20d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":306,
                  "y":154},
                "size":{
                  "width":327,
                  "height":38},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一手房-新盘速递/u17.png"}},
{
          "id":"e591926ea8544b2db954d60885c0e71a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":364,
              "y":162},
            "size":{
              "width":236,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9ce9b031f364b6fa698f0f526c1fe6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":364,
                  "y":162},
                "size":{
                  "width":236,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aaca79201ce24bbf90be773a66f672af",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":412,
              "y":645},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14a369099e3c4fa48aa5513ec4749324",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":412,
                  "y":645},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8492c706608549f7a63b5c7d6ea5fc87",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":519,
              "y":321},
            "size":{
              "width":10,
              "height":21}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新房速递-详情/u20_line.png"}},
{
          "id":"5ebc57014cea41989d31bf9d26a2ce9d",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":404,
              "y":322},
            "size":{
              "width":10,
              "height":21}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新房速递-详情/u20_line.png"}},
{
          "id":"7d186023aff04b20860e6921a7922f5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":456,
              "y":266},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"107cfd49ebae411e8b064d31a9f50022",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":456,
                  "y":266},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"838eec3b052448b39cfca19798f52a14",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":454,
              "y":324},
            "size":{
              "width":52,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98207f60099c44849d85d424a1c872c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":454,
                  "y":324},
                "size":{
                  "width":52,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ada494def1144befa1bcd7b318b31b81",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":306,
              "y":346},
            "size":{
              "width":322,
              "height":179}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68d524073d89454b9046cef5c02e3f37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":306,
                  "y":346},
                "size":{
                  "width":322,
                  "height":179}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新房速递-详情/u26.png"}},
{
          "id":"a6b4643ce9024259add0410f5131bb23",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":346},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17c95c1973704cc4977e55e99de45d95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":308,
                  "y":346},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6899800e17b7448fb5a19149f8f290c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":431},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6fa66a62e8b4eb9aafecd5adc3eca31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":308,
                  "y":431},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7a9a9e95b1146b0b08eae0460dc292b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":383},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81b05b8a0b8040a491e272f0c3fe6605",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":308,
                  "y":383},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9e937d7b1d2450e9f0347e4b2dfd557",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":307,
              "y":364},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50488bf764414038a1afd673a475f62d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":307,
                  "y":364},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"353946b904f24943ac84d5face6e3866",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":494,
              "y":417},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f953bb6cffaa41dd99081bebb875bfa6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":494,
                  "y":417},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"309b19ed34b349bb8ebdfbc5e69eafe5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":398},
            "size":{
              "width":200,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1322016ce4644ba487eb1cceeed61374",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":308,
                  "y":398},
                "size":{
                  "width":200,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3066197200a402b90f17d8f8c6b9af5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":494,
              "y":411},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"066dcda335e049c39bfe78b486fdcb7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":494,
                  "y":411},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"51952c3fbff745cdac9978cc1336e95b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCFF99},
            "location":{
              "x":416,
              "y":640},
            "size":{
              "width":108,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"009b5940dc4d416799ac67d3b413fc4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCFF99},
                "location":{
                  "x":416,
                  "y":640},
                "size":{
                  "width":108,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新房速递-详情/u42.png"}},
{
          "id":"349186798758438db9d3b000e469f102",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF006699},
            "location":{
              "x":524,
              "y":640},
            "size":{
              "width":105,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db8eee60a54a48e8be0be1410c1b1e11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF006699},
                "location":{
                  "x":524,
                  "y":640},
                "size":{
                  "width":105,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新房速递-详情/u44.png"}},
{
          "id":"090cde1f8fbe434e8dd7042a831f69f3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":192},
            "size":{
              "width":322,
              "height":71},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0843d784b6a42febfcfbd04c7a9c91e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":308,
                  "y":192},
                "size":{
                  "width":322,
                  "height":71},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新房速递-详情/u46.png"}},
{
          "id":"4de3bbe4b93b4d92b33025e6984df2bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "location":{
              "x":494,
              "y":264},
            "size":{
              "width":150,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb3ee5bf0f6c49f7b160915ce5485ec5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "location":{
                  "x":494,
                  "y":264},
                "size":{
                  "width":150,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f04319ebd04c4381b81158ff31ca06a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":308,
              "y":282},
            "size":{
              "width":314,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b603281485cb4fb1aba183374a46f308",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":308,
                  "y":282},
                "size":{
                  "width":314,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ccfe07c3a3e740529d8f05f76594ad44",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":458},
            "size":{
              "width":314,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0ff1e1e91614c02b4dc24883d654595",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":309,
                  "y":458},
                "size":{
                  "width":314,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"013cfe3091f646b2a8a4b3558573fdc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":418},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"520e5fa92b4b4e79b0d095878146746a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":308,
                  "y":418},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"adf1e912fd5341ef9835a635c6ef0955",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":306,
              "y":439},
            "size":{
              "width":152,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4cc23629da04e88afac5ab6587f7fcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":306,
                  "y":439},
                "size":{
                  "width":152,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7bff991e226f42db8da5e519b5aa4090",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":494,
              "y":438},
            "size":{
              "width":152,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcdfbc7f343f4b8fadeaf49094dd1229",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":494,
                  "y":438},
                "size":{
                  "width":152,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a701f115af194ea48d707d0f9432956b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":445.5,
              "y":208.5},
            "size":{
              "width":39,
              "height":31},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e18775892268489c913bc1867a09cc01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":445.5,
                  "y":208.5},
                "size":{
                  "width":39,
                  "height":31},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新房速递-详情/u60.png"}},
{
          "id":"b878334b772345f88b778a2d7c068477",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":548},
            "size":{
              "width":324,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新房速递-详情/u62_line.png"}},
{
          "id":"e7e67c261036497ba9181209feed6c5c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":527},
            "size":{
              "width":12,
              "height":24},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d59163ce928146e2b618e66e09f81b2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":610,
                  "y":527},
                "size":{
                  "width":12,
                  "height":24},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新房速递-详情/u63.png"}},
{
          "id":"14e563d670a24b6a8bc597678d9743cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":311,
              "y":529},
            "size":{
              "width":261,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ef013f2d18d43259baf40b6e67ac760",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":311,
                  "y":529},
                "size":{
                  "width":261,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6f54dae90c94e559c94aeb8deff6e13",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":507,
              "y":216},
            "size":{
              "width":137,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ced6fdf9d34f4b39949c9f741b43547c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":507,
                  "y":216},
                "size":{
                  "width":137,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ac96d1fead542c2b33b1405ac4f3c9e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":315},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新房速递-详情/u69_line.png"}},
{
          "id":"04fc22dbf8894487b64d96630d4d15cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":869,
              "y":124},
            "size":{
              "width":81,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04b2874ec427414cbfda7a93fb23ac45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":869,
                  "y":124},
                "size":{
                  "width":81,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6c4b986537b463aaae8ecdb8d008c0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'AvantGarde Bk BT Book', 'AvantGarde Bk BT'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":762,
              "y":115},
            "size":{
              "width":23,
              "height":34},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ae2e9c8341e44b4ae0b4326cbef4709",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'AvantGarde Bk BT Book', 'AvantGarde Bk BT'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":762,
                  "y":115},
                "size":{
                  "width":23,
                  "height":34},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"738c7dbd2f334a44a26998a3d3f8707a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":710,
              "y":11},
            "size":{
              "width":405,
              "height":776},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b807aa97cb2b4fe1bf7b38cb4d6d56cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":710,
                  "y":11},
                "size":{
                  "width":405,
                  "height":776},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信首页-一_展示区/u8.png"}},
{
          "id":"3407955c8cce4ab78a77ec20986dafa4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":820,
              "y":124},
            "size":{
              "width":100,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f81842a6e924b11be6738d2997a958f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":820,
                  "y":124},
                "size":{
                  "width":100,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9190e747c6bf4b1eb292b0d256787a69",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'AvantGarde Bk BT Book', 'AvantGarde Bk BT'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":755,
              "y":115},
            "size":{
              "width":23,
              "height":34},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c0e21d9a71b407a8cc1a39f6c48f46d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'AvantGarde Bk BT Book', 'AvantGarde Bk BT'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":755,
                  "y":115},
                "size":{
                  "width":23,
                  "height":34},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8a0c517770846b6ad62dc70ef713240",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":749,
              "y":154},
            "size":{
              "width":323,
              "height":520}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e677d2d9b204f78b5b788bf07473896",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":749,
                  "y":154},
                "size":{
                  "width":323,
                  "height":520}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信首页-一_展示区/u14.png"}},
{
          "id":"45a832d056bb4275843242ec71ae90d0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":778,
              "y":113},
            "size":{
              "width":41,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e613c80ae8a41e58187c6982ca06b7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":778,
                  "y":113},
                "size":{
                  "width":41,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信首页-一_展示区/u26.png"}},
{
          "id":"87f303cabc5944328b8cafa729327e44",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":748,
              "y":154},
            "size":{
              "width":327,
              "height":38},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9a0bf485c564ddea65399815fa18917",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":748,
                  "y":154},
                "size":{
                  "width":327,
                  "height":38},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一手房-新盘速递/u17.png"}},
{
          "id":"ac592cd608424949a3ef02a5de6e8a68",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":892,
              "y":266},
            "size":{
              "width":180,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ad14e48e31b4c14ac315d9466fbc5d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":892,
                  "y":266},
                "size":{
                  "width":180,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新房速递-详情/u86.png"}},
{
          "id":"8a4630d7effa45cda34ae3393a7bab15",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":752,
              "y":267},
            "size":{
              "width":140,
              "height":39},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0435ffd1b22443e944d6f35a74bab37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":752,
                  "y":267},
                "size":{
                  "width":140,
                  "height":39},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新房速递-详情/u46.png"}},
{
          "id":"963754ba94b64f65b8e73013740c3417",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":746,
              "y":184},
            "size":{
              "width":331,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新房速递-详情/u90_line.png"}},
{
          "id":"c68610aa28fa46759958559503232b24",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":800,
              "y":271},
            "size":{
              "width":39,
              "height":31},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b15d49734fd4a678041856e2e9aeead",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":800,
                  "y":271},
                "size":{
                  "width":39,
                  "height":31},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新房速递-详情/u60.png"}},
{
          "id":"e21c8070477a4ae28ddf3d4cc4f1bdde",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":966,
              "y":270},
            "size":{
              "width":137,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b82873d861e4eee8047a0928cc7570c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":966,
                  "y":270},
                "size":{
                  "width":137,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a44b3c2158c49e89233c665da269282",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":896,
              "y":274},
            "size":{
              "width":62,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dff2fab92d8947c88b891d6334d3dcb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":896,
                  "y":274},
                "size":{
                  "width":62,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a425ec9b3e2a4486b817e565836725a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC99},
            "location":{
              "x":750,
              "y":640},
            "size":{
              "width":110,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"967771d0546c4596bb6df04ff0be46e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC99},
                "location":{
                  "x":750,
                  "y":640},
                "size":{
                  "width":110,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新房速递-详情/u97.png"}},
{
          "id":"9577a372b9c749f381b4a2d722411fa2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCFF99},
            "location":{
              "x":860,
              "y":640},
            "size":{
              "width":108,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"393a8766b8594719a1ffa503922cff31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCFF99},
                "location":{
                  "x":860,
                  "y":640},
                "size":{
                  "width":108,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新房速递-详情/u42.png"}},
{
          "id":"688aa49335b247419c743377b42cb9b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF006699},
            "location":{
              "x":968,
              "y":640},
            "size":{
              "width":109,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f65717a1b1634e7f9f195a278b273cca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF006699},
                "location":{
                  "x":968,
                  "y":640},
                "size":{
                  "width":109,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新房速递-详情/u101.png"}},
{
          "id":"f1b81fd3a5bf495482d16f188b8a91f0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":751,
              "y":310},
            "size":{
              "width":140,
              "height":39},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad218760ccff4226bbd1ae0dd96eb0ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":751,
                  "y":310},
                "size":{
                  "width":140,
                  "height":39},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新房速递-详情/u46.png"}},
{
          "id":"2fcdcc5a50404d448dda8d64a524597a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":892,
              "y":309},
            "size":{
              "width":180,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e12c7c5ea3294275be46d58bfc7dad27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":892,
                  "y":309},
                "size":{
                  "width":180,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新房速递-详情/u86.png"}},
{
          "id":"a43d42a71f6940e2ab8662d07846a45e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":895,
              "y":317},
            "size":{
              "width":79,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07b5f4badbb440cfa92c1f35b2406075",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":895,
                  "y":317},
                "size":{
                  "width":79,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50084e231b34447d8d93862c1fd19828",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":969,
              "y":312},
            "size":{
              "width":137,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46c1c935f18146b6ad96a3309f40434e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":969,
                  "y":312},
                "size":{
                  "width":137,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd134edfb59042df895dc66f4c4f5518",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":751,
              "y":354},
            "size":{
              "width":140,
              "height":39},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e421148e1b444bbbb460a7d7ee6d2f60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":751,
                  "y":354},
                "size":{
                  "width":140,
                  "height":39},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新房速递-详情/u46.png"}},
{
          "id":"1450dffd30f14739b0b605fe9ca664da",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":353},
            "size":{
              "width":180,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b4629b9c666479baecb91dc40c90ca3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":890,
                  "y":353},
                "size":{
                  "width":180,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新房速递-详情/u86.png"}},
{
          "id":"c6c50c16eebe4fb68a803b054a328037",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":893,
              "y":361},
            "size":{
              "width":79,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cdd0b19aa9249429acc9d9393ea9611",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":893,
                  "y":361},
                "size":{
                  "width":79,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"07ce478435ea49abb9a92663c3bdc8ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":972,
              "y":355},
            "size":{
              "width":137,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd98ce77379248fd9e7b27636ec42a2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":972,
                  "y":355},
                "size":{
                  "width":137,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d15c5eb262e84a9fa3ca6ca8bb4f0589",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":799,
              "y":317},
            "size":{
              "width":39,
              "height":31},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8813731323e341b4a44434657962e34b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":799,
                  "y":317},
                "size":{
                  "width":39,
                  "height":31},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新房速递-详情/u60.png"}},
{
          "id":"8d2336e1152743a0a6c8e3858cad6a75",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":798,
              "y":358},
            "size":{
              "width":39,
              "height":31},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"915ef136d5bc407b9ec77c8c0587e585",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":798,
                  "y":358},
                "size":{
                  "width":39,
                  "height":31},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新房速递-详情/u60.png"}},
{
          "id":"691cca1c11074bb8b832acc4508100c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":809,
              "y":162},
            "size":{
              "width":236,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9348b8b801c140aaa3ad24b28037509d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":809,
                  "y":162},
                "size":{
                  "width":236,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5445d235cfc14903a15ccb558f313226",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":310,
              "y":262},
            "size":{
              "width":303,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83ac2bff48144bb8bf09ca38342f45fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":310,
                  "y":262},
                "size":{
                  "width":303,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2f5c943a49a4ccebf4138e27848e957",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":328},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3bc2ed550e24a08a30a311bb2d0cb95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":328},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4efde6e7c69e424da344e190e6319325",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":325},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79803a8bfb824662bd00bb40ae201397",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":325},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba7544ccecc048a89fb7851dc57ddc7c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":600},
            "size":{
              "width":324,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新房速递-详情/u62_line.png"}},
{
          "id":"d304d4a2235b4f55822d9f329e2f2cfd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":314,
              "y":554},
            "size":{
              "width":60,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"458819060c624392bf6fcbcaf000a6cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":314,
                  "y":554},
                "size":{
                  "width":60,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新房速递-详情/u132.png"}},
{
          "id":"79020e081fca4d78ab9df90e0e0c1438",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":392,
              "y":558},
            "size":{
              "width":49,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0d4f788892047c39f556e0b1b3ed850",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":392,
                  "y":558},
                "size":{
                  "width":49,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"75e02f15bc2445f4a5a621e7bebd5198",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":392,
              "y":584},
            "size":{
              "width":61,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cf6d4cf55274957a783be9768b1b5c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":392,
                  "y":584},
                "size":{
                  "width":61,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"393852ed6edb4234b9e22c9517b0718c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":314,
              "y":604},
            "size":{
              "width":60,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d44fbbf414164613a2acc6d7aedad813",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":314,
                  "y":604},
                "size":{
                  "width":60,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新房速递-详情/u132.png"}},
{
          "id":"d71d2e6d3d1342e5bbc34b41a9f267bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC99},
            "location":{
              "x":309,
              "y":640},
            "size":{
              "width":107,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d8117e2c7004dd8829d31fccf36d615",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC99},
                "location":{
                  "x":309,
                  "y":640},
                "size":{
                  "width":107,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新房速递-详情/u140.png"}},
{
          "id":"d94b0021c61f44af922a64e0a075f283",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":392,
              "y":609},
            "size":{
              "width":49,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72700c4f4b324e7294cbdd4af0efd576",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":392,
                  "y":609},
                "size":{
                  "width":49,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5721ca78a8e94088a2ea8581eec42785",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":393,
              "y":623},
            "size":{
              "width":61,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25148d3c3ad54ad0943159dff61ff8b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":393,
                  "y":623},
                "size":{
                  "width":61,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b44e97c7fbf34da1b78816b87a903888",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":308,
              "y":299},
            "size":{
              "width":314,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9d7c747dfcc419a93c82e9f19d8022f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":308,
                  "y":299},
                "size":{
                  "width":314,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"241cf9160fb7471e9f2b0c285a9f7c78",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":474},
            "size":{
              "width":313,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adf6b023d8334baf8fe57037ec679ceb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":309,
                  "y":474},
                "size":{
                  "width":313,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新房速递-详情/u148.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "ebf0cfdbdb9644708182e1c3796e8acf":{
      "scriptId":"u0"},
    "d659321250284dc2b79da5202c161647":{
      "scriptId":"u1"},
    "4d2dce6eae0a4ec7920a6c9a3a0ab5ba":{
      "scriptId":"u2"},
    "3c5469ca0de14c0e8a219b9414c31d93":{
      "scriptId":"u3"},
    "4bbf9d025bf44e11a1809ec1b8eba61f":{
      "scriptId":"u4"},
    "4e12d31197c54102ae97eb065ae19da4":{
      "scriptId":"u5"},
    "b5deea1e2fa443bd836528f42925acaf":{
      "scriptId":"u6"},
    "fd5c7418db664b91a0cff91deb759d4d":{
      "scriptId":"u7"},
    "8f678210757a40e9ac30d38684b8791e":{
      "scriptId":"u8"},
    "9d15073682724722a17683d3161ad825":{
      "scriptId":"u9"},
    "3adc064d71104b2397070efd8992bb17":{
      "scriptId":"u10"},
    "2c52e6bd285e4d8680e1c022cd589e6e":{
      "scriptId":"u11"},
    "c8dfe850d8f94c55ac256c8c77bd470d":{
      "scriptId":"u12"},
    "109fe0e630354a73a7d7e8e88b2dd3fc":{
      "scriptId":"u13"},
    "9b8413ed89294754bf1016c786511823":{
      "scriptId":"u14"},
    "31bed65ff0f249c490e7234ea03c20d9":{
      "scriptId":"u15"},
    "e591926ea8544b2db954d60885c0e71a":{
      "scriptId":"u16"},
    "b9ce9b031f364b6fa698f0f526c1fe6b":{
      "scriptId":"u17"},
    "aaca79201ce24bbf90be773a66f672af":{
      "scriptId":"u18"},
    "14a369099e3c4fa48aa5513ec4749324":{
      "scriptId":"u19"},
    "8492c706608549f7a63b5c7d6ea5fc87":{
      "scriptId":"u20"},
    "5ebc57014cea41989d31bf9d26a2ce9d":{
      "scriptId":"u21"},
    "7d186023aff04b20860e6921a7922f5c":{
      "scriptId":"u22"},
    "107cfd49ebae411e8b064d31a9f50022":{
      "scriptId":"u23"},
    "838eec3b052448b39cfca19798f52a14":{
      "scriptId":"u24"},
    "98207f60099c44849d85d424a1c872c0":{
      "scriptId":"u25"},
    "ada494def1144befa1bcd7b318b31b81":{
      "scriptId":"u26"},
    "68d524073d89454b9046cef5c02e3f37":{
      "scriptId":"u27"},
    "a6b4643ce9024259add0410f5131bb23":{
      "scriptId":"u28"},
    "17c95c1973704cc4977e55e99de45d95":{
      "scriptId":"u29"},
    "6899800e17b7448fb5a19149f8f290c3":{
      "scriptId":"u30"},
    "c6fa66a62e8b4eb9aafecd5adc3eca31":{
      "scriptId":"u31"},
    "b7a9a9e95b1146b0b08eae0460dc292b":{
      "scriptId":"u32"},
    "81b05b8a0b8040a491e272f0c3fe6605":{
      "scriptId":"u33"},
    "c9e937d7b1d2450e9f0347e4b2dfd557":{
      "scriptId":"u34"},
    "50488bf764414038a1afd673a475f62d":{
      "scriptId":"u35"},
    "353946b904f24943ac84d5face6e3866":{
      "scriptId":"u36"},
    "f953bb6cffaa41dd99081bebb875bfa6":{
      "scriptId":"u37"},
    "309b19ed34b349bb8ebdfbc5e69eafe5":{
      "scriptId":"u38"},
    "1322016ce4644ba487eb1cceeed61374":{
      "scriptId":"u39"},
    "e3066197200a402b90f17d8f8c6b9af5":{
      "scriptId":"u40"},
    "066dcda335e049c39bfe78b486fdcb7b":{
      "scriptId":"u41"},
    "51952c3fbff745cdac9978cc1336e95b":{
      "scriptId":"u42"},
    "009b5940dc4d416799ac67d3b413fc4c":{
      "scriptId":"u43"},
    "349186798758438db9d3b000e469f102":{
      "scriptId":"u44"},
    "db8eee60a54a48e8be0be1410c1b1e11":{
      "scriptId":"u45"},
    "090cde1f8fbe434e8dd7042a831f69f3":{
      "scriptId":"u46"},
    "e0843d784b6a42febfcfbd04c7a9c91e":{
      "scriptId":"u47"},
    "4de3bbe4b93b4d92b33025e6984df2bd":{
      "scriptId":"u48"},
    "cb3ee5bf0f6c49f7b160915ce5485ec5":{
      "scriptId":"u49"},
    "f04319ebd04c4381b81158ff31ca06a0":{
      "scriptId":"u50"},
    "b603281485cb4fb1aba183374a46f308":{
      "scriptId":"u51"},
    "ccfe07c3a3e740529d8f05f76594ad44":{
      "scriptId":"u52"},
    "f0ff1e1e91614c02b4dc24883d654595":{
      "scriptId":"u53"},
    "013cfe3091f646b2a8a4b3558573fdc1":{
      "scriptId":"u54"},
    "520e5fa92b4b4e79b0d095878146746a":{
      "scriptId":"u55"},
    "adf1e912fd5341ef9835a635c6ef0955":{
      "scriptId":"u56"},
    "b4cc23629da04e88afac5ab6587f7fcb":{
      "scriptId":"u57"},
    "7bff991e226f42db8da5e519b5aa4090":{
      "scriptId":"u58"},
    "bcdfbc7f343f4b8fadeaf49094dd1229":{
      "scriptId":"u59"},
    "a701f115af194ea48d707d0f9432956b":{
      "scriptId":"u60"},
    "e18775892268489c913bc1867a09cc01":{
      "scriptId":"u61"},
    "b878334b772345f88b778a2d7c068477":{
      "scriptId":"u62"},
    "e7e67c261036497ba9181209feed6c5c":{
      "scriptId":"u63"},
    "d59163ce928146e2b618e66e09f81b2e":{
      "scriptId":"u64"},
    "14e563d670a24b6a8bc597678d9743cb":{
      "scriptId":"u65"},
    "1ef013f2d18d43259baf40b6e67ac760":{
      "scriptId":"u66"},
    "d6f54dae90c94e559c94aeb8deff6e13":{
      "scriptId":"u67"},
    "ced6fdf9d34f4b39949c9f741b43547c":{
      "scriptId":"u68"},
    "9ac96d1fead542c2b33b1405ac4f3c9e":{
      "scriptId":"u69"},
    "04fc22dbf8894487b64d96630d4d15cd":{
      "scriptId":"u70"},
    "04b2874ec427414cbfda7a93fb23ac45":{
      "scriptId":"u71"},
    "c6c4b986537b463aaae8ecdb8d008c0e":{
      "scriptId":"u72"},
    "7ae2e9c8341e44b4ae0b4326cbef4709":{
      "scriptId":"u73"},
    "738c7dbd2f334a44a26998a3d3f8707a":{
      "scriptId":"u74"},
    "b807aa97cb2b4fe1bf7b38cb4d6d56cf":{
      "scriptId":"u75"},
    "3407955c8cce4ab78a77ec20986dafa4":{
      "scriptId":"u76"},
    "3f81842a6e924b11be6738d2997a958f":{
      "scriptId":"u77"},
    "9190e747c6bf4b1eb292b0d256787a69":{
      "scriptId":"u78"},
    "4c0e21d9a71b407a8cc1a39f6c48f46d":{
      "scriptId":"u79"},
    "d8a0c517770846b6ad62dc70ef713240":{
      "scriptId":"u80"},
    "9e677d2d9b204f78b5b788bf07473896":{
      "scriptId":"u81"},
    "45a832d056bb4275843242ec71ae90d0":{
      "scriptId":"u82"},
    "8e613c80ae8a41e58187c6982ca06b7c":{
      "scriptId":"u83"},
    "87f303cabc5944328b8cafa729327e44":{
      "scriptId":"u84"},
    "a9a0bf485c564ddea65399815fa18917":{
      "scriptId":"u85"},
    "ac592cd608424949a3ef02a5de6e8a68":{
      "scriptId":"u86"},
    "9ad14e48e31b4c14ac315d9466fbc5d6":{
      "scriptId":"u87"},
    "8a4630d7effa45cda34ae3393a7bab15":{
      "scriptId":"u88"},
    "d0435ffd1b22443e944d6f35a74bab37":{
      "scriptId":"u89"},
    "963754ba94b64f65b8e73013740c3417":{
      "scriptId":"u90"},
    "c68610aa28fa46759958559503232b24":{
      "scriptId":"u91"},
    "7b15d49734fd4a678041856e2e9aeead":{
      "scriptId":"u92"},
    "e21c8070477a4ae28ddf3d4cc4f1bdde":{
      "scriptId":"u93"},
    "5b82873d861e4eee8047a0928cc7570c":{
      "scriptId":"u94"},
    "1a44b3c2158c49e89233c665da269282":{
      "scriptId":"u95"},
    "dff2fab92d8947c88b891d6334d3dcb8":{
      "scriptId":"u96"},
    "a425ec9b3e2a4486b817e565836725a8":{
      "scriptId":"u97"},
    "967771d0546c4596bb6df04ff0be46e3":{
      "scriptId":"u98"},
    "9577a372b9c749f381b4a2d722411fa2":{
      "scriptId":"u99"},
    "393a8766b8594719a1ffa503922cff31":{
      "scriptId":"u100"},
    "688aa49335b247419c743377b42cb9b0":{
      "scriptId":"u101"},
    "f65717a1b1634e7f9f195a278b273cca":{
      "scriptId":"u102"},
    "f1b81fd3a5bf495482d16f188b8a91f0":{
      "scriptId":"u103"},
    "ad218760ccff4226bbd1ae0dd96eb0ef":{
      "scriptId":"u104"},
    "2fcdcc5a50404d448dda8d64a524597a":{
      "scriptId":"u105"},
    "e12c7c5ea3294275be46d58bfc7dad27":{
      "scriptId":"u106"},
    "a43d42a71f6940e2ab8662d07846a45e":{
      "scriptId":"u107"},
    "07b5f4badbb440cfa92c1f35b2406075":{
      "scriptId":"u108"},
    "50084e231b34447d8d93862c1fd19828":{
      "scriptId":"u109"},
    "46c1c935f18146b6ad96a3309f40434e":{
      "scriptId":"u110"},
    "bd134edfb59042df895dc66f4c4f5518":{
      "scriptId":"u111"},
    "e421148e1b444bbbb460a7d7ee6d2f60":{
      "scriptId":"u112"},
    "1450dffd30f14739b0b605fe9ca664da":{
      "scriptId":"u113"},
    "3b4629b9c666479baecb91dc40c90ca3":{
      "scriptId":"u114"},
    "c6c50c16eebe4fb68a803b054a328037":{
      "scriptId":"u115"},
    "1cdd0b19aa9249429acc9d9393ea9611":{
      "scriptId":"u116"},
    "07ce478435ea49abb9a92663c3bdc8ec":{
      "scriptId":"u117"},
    "cd98ce77379248fd9e7b27636ec42a2d":{
      "scriptId":"u118"},
    "d15c5eb262e84a9fa3ca6ca8bb4f0589":{
      "scriptId":"u119"},
    "8813731323e341b4a44434657962e34b":{
      "scriptId":"u120"},
    "8d2336e1152743a0a6c8e3858cad6a75":{
      "scriptId":"u121"},
    "915ef136d5bc407b9ec77c8c0587e585":{
      "scriptId":"u122"},
    "691cca1c11074bb8b832acc4508100c1":{
      "scriptId":"u123"},
    "9348b8b801c140aaa3ad24b28037509d":{
      "scriptId":"u124"},
    "5445d235cfc14903a15ccb558f313226":{
      "scriptId":"u125"},
    "83ac2bff48144bb8bf09ca38342f45fa":{
      "scriptId":"u126"},
    "e2f5c943a49a4ccebf4138e27848e957":{
      "scriptId":"u127"},
    "d3bc2ed550e24a08a30a311bb2d0cb95":{
      "scriptId":"u128"},
    "4efde6e7c69e424da344e190e6319325":{
      "scriptId":"u129"},
    "79803a8bfb824662bd00bb40ae201397":{
      "scriptId":"u130"},
    "ba7544ccecc048a89fb7851dc57ddc7c":{
      "scriptId":"u131"},
    "d304d4a2235b4f55822d9f329e2f2cfd":{
      "scriptId":"u132"},
    "458819060c624392bf6fcbcaf000a6cf":{
      "scriptId":"u133"},
    "79020e081fca4d78ab9df90e0e0c1438":{
      "scriptId":"u134"},
    "a0d4f788892047c39f556e0b1b3ed850":{
      "scriptId":"u135"},
    "75e02f15bc2445f4a5a621e7bebd5198":{
      "scriptId":"u136"},
    "5cf6d4cf55274957a783be9768b1b5c9":{
      "scriptId":"u137"},
    "393852ed6edb4234b9e22c9517b0718c":{
      "scriptId":"u138"},
    "d44fbbf414164613a2acc6d7aedad813":{
      "scriptId":"u139"},
    "d71d2e6d3d1342e5bbc34b41a9f267bd":{
      "scriptId":"u140"},
    "2d8117e2c7004dd8829d31fccf36d615":{
      "scriptId":"u141"},
    "d94b0021c61f44af922a64e0a075f283":{
      "scriptId":"u142"},
    "72700c4f4b324e7294cbdd4af0efd576":{
      "scriptId":"u143"},
    "5721ca78a8e94088a2ea8581eec42785":{
      "scriptId":"u144"},
    "25148d3c3ad54ad0943159dff61ff8b2":{
      "scriptId":"u145"},
    "b44e97c7fbf34da1b78816b87a903888":{
      "scriptId":"u146"},
    "c9d7c747dfcc419a93c82e9f19d8022f":{
      "scriptId":"u147"},
    "241cf9160fb7471e9f2b0c285a9f7c78":{
      "scriptId":"u148"},
    "adf6b023d8334baf8fe57037ec679ceb":{
      "scriptId":"u149"}}});