<?php
return array (
  0 => 'app_id',
  1 => 'app_name',
  2 => 'app_alias',
  3 => 'description',
  4 => 'version',
  5 => 'status',
  6 => 'category',
  7 => 'release_date',
  8 => 'last_update_date',
  9 => 'host_type',
  10 => 'app_entry',
  11 => 'icon_url',
  12 => 'large_icon_url',
  13 => 'admin_entry',
  14 => 'statistics_entry',
  15 => 'homepage_url',
  16 => 'sidebar_title',
  17 => 'sidebar_entry',
  18 => 'sidebar_icon_url',
  19 => 'sidebar_support_submenu',
  20 => 'sidebar_is_submenu_active',
  21 => 'author_name',
  22 => 'author_email',
  23 => 'author_homepage_url',
  24 => 'contributor_name',
  25 => 'display_order',
  26 => 'ctime',
  '_autoinc' => true,
  '_pk' => 'app_id',
);
?>