<?php
return array (
  0 => 'uid',
  1 => 'email',
  2 => 'password',
  3 => 'uname',
  4 => 'pid',
  5 => 'head_pic_url',
  6 => 'sex',
  7 => 'birth',
  8 => 'province',
  9 => 'city',
  10 => 'location',
  11 => 'cellphone',
  12 => 'telephone',
  13 => 'company',
  14 => 'position',
  15 => 'industry',
  16 => 'indust_id',
  17 => 'admin_level',
  18 => 'commend',
  19 => 'is_active',
  20 => 'is_init',
  21 => 'is_synchronizing',
  22 => 'ctime',
  23 => 'identity',
  24 => 'score',
  25 => 'myop_menu_num',
  26 => 'api_key',
  27 => 'domain',
  28 => 'recommend',
  29 => 'is_avatar',
  '_autoinc' => true,
  '_pk' => 'uid',
);
?>