$axure.loadCurrentPage({
  "url":"一手房-直播间.html",
  "generationDate":new Date(1408598586192.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"27b985d16d034ae489daef4ae61c7af3",
    "type":"Axure:Page",
    "name":"一手房-直播间",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1c3f81d6865f43e48ac5ade288f16fb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":427,
              "y":124},
            "size":{
              "width":81,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29c094fc46204abab5cb8184c7b39fca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":427,
                  "y":124},
                "size":{
                  "width":81,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b445b7b985c4a939d313f3741010f83",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'AvantGarde Bk BT Book', 'AvantGarde Bk BT'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":320,
              "y":115},
            "size":{
              "width":23,
              "height":34},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a883d74d6974d39850dc74fb39b8af4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'AvantGarde Bk BT Book', 'AvantGarde Bk BT'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":320,
                  "y":115},
                "size":{
                  "width":23,
                  "height":34},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54e55945f053472b8f6732116a041f40",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":11},
            "size":{
              "width":405,
              "height":776},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d4954d9f9224400be1f1be67c190818",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":268,
                  "y":11},
                "size":{
                  "width":405,
                  "height":776},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信首页-一_展示区/u8.png"}},
{
          "id":"fcbd10169d7c4e50a8ba773f2cb0593d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":378,
              "y":124},
            "size":{
              "width":100,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b38f3bb815f646b78e810f984edf3eb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":378,
                  "y":124},
                "size":{
                  "width":100,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f413d0a71537470688815ac3dc84e71c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'AvantGarde Bk BT Book', 'AvantGarde Bk BT'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":313,
              "y":115},
            "size":{
              "width":23,
              "height":34},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad0df6cde9224f259dea8ac89206945f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'AvantGarde Bk BT Book', 'AvantGarde Bk BT'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":313,
                  "y":115},
                "size":{
                  "width":23,
                  "height":34},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99922959858b4455afa91d8c1e4b0259",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":307,
              "y":154},
            "size":{
              "width":323,
              "height":520}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b897702d3824097a5048cd4753a4165",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":307,
                  "y":154},
                "size":{
                  "width":323,
                  "height":520}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信首页-一_展示区/u14.png"}},
{
          "id":"a90ba30c39cb450ca3b5e4830f411875",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":336,
              "y":113},
            "size":{
              "width":41,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe8eb8fd60e64765b24ce9dc2c5a3118",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":336,
                  "y":113},
                "size":{
                  "width":41,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信首页-一_展示区/u26.png"}},
{
          "id":"831d34d344f34999ab1dd47b0e3a99bc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":306,
              "y":154},
            "size":{
              "width":327,
              "height":38},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ccc262cd7254129924cca15ffde3f43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":306,
                  "y":154},
                "size":{
                  "width":327,
                  "height":38},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一手房-新盘速递/u17.png"}},
{
          "id":"096b0138e26d4c29b3cd90136a896e29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":398,
              "y":162},
            "size":{
              "width":173,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f92c8c5576c04739ad4545681f665c93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":398,
                  "y":162},
                "size":{
                  "width":173,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"932781e5825c4eb09d411a73bff588d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":311,
              "y":229},
            "size":{
              "width":317,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43e5d5610fba4e2b929be872b4a83c9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":311,
                  "y":229},
                "size":{
                  "width":317,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一手房-直播间/u18.png"}},
{
          "id":"6405ab3590cd4fb7a83c983cdf391b6f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":304,
              "y":184},
            "size":{
              "width":331,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新房速递-详情/u90_line.png"}},
{
          "id":"a70b7c0ca05248cfa78e39063d1d4cc2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC99},
            "location":{
              "x":304,
              "y":640},
            "size":{
              "width":164,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15b7ebad01b848cdbbaf1eed2897cd6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC99},
                "location":{
                  "x":304,
                  "y":640},
                "size":{
                  "width":164,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一手房-直播间/u21.png"}},
{
          "id":"12e1f761fa7149549fd6c1522d26e795",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF006699},
            "location":{
              "x":468,
              "y":640},
            "size":{
              "width":163,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"823826bc41a84e0a9897ea443f1e9499",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF006699},
                "location":{
                  "x":468,
                  "y":640},
                "size":{
                  "width":163,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一手房-直播间/u23.png"}},
{
          "id":"ec31e9da68904657b04db5ae6ca8f62f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":326,
              "y":233},
            "size":{
              "width":162,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6334e22844b44442b281195aa7a9bb86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":326,
                  "y":233},
                "size":{
                  "width":162,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed872e0e6f00422881c79966f5b9f401",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":312,
              "y":270},
            "size":{
              "width":317,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2a300923d824eefb43321f818acee51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":312,
                  "y":270},
                "size":{
                  "width":317,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一手房-直播间/u18.png"}},
{
          "id":"62a4708829834bba86a14e5649a61016",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":328,
              "y":274},
            "size":{
              "width":162,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ce599d2f0d54177a801551a67595ccd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":328,
                  "y":274},
                "size":{
                  "width":162,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80d8f43f67104b5083e737569acf1e05",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":312,
              "y":316},
            "size":{
              "width":317,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d62ca94627074bb2a068e14f106cbc69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":312,
                  "y":316},
                "size":{
                  "width":317,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一手房-直播间/u18.png"}},
{
          "id":"ae3456cb622a404b969ff3471f857765",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":328,
              "y":320},
            "size":{
              "width":162,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5bf5096575b427bab6ea09bdde8382f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":328,
                  "y":320},
                "size":{
                  "width":162,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f4eb042b98b8434abd1dcd354a555480",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1279,
              "y":124},
            "size":{
              "width":81,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b48ae252a1f482390e5cf1858f084da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1279,
                  "y":124},
                "size":{
                  "width":81,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5cdb023fe40b488c99b74be445778057",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'AvantGarde Bk BT Book', 'AvantGarde Bk BT'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1172,
              "y":115},
            "size":{
              "width":23,
              "height":34},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67785ed0351647c28b418ea91fb0c819",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'AvantGarde Bk BT Book', 'AvantGarde Bk BT'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1172,
                  "y":115},
                "size":{
                  "width":23,
                  "height":34},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"24cef320858945148eb5a0fc27c9d0d1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1120,
              "y":11},
            "size":{
              "width":405,
              "height":776},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"542dec13409a4c058b4f662d863ac640",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1120,
                  "y":11},
                "size":{
                  "width":405,
                  "height":776},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信首页-一_展示区/u8.png"}},
{
          "id":"68a43a067f0f46e9aeb69cbf0f3cfba0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1230,
              "y":124},
            "size":{
              "width":100,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"603cae258fc64fbb939f08bcbcaa01a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1230,
                  "y":124},
                "size":{
                  "width":100,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"15398f385188449fb93d45897574110d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'AvantGarde Bk BT Book', 'AvantGarde Bk BT'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1165,
              "y":115},
            "size":{
              "width":23,
              "height":34},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e5536d7495640238f216676bf82d40f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'AvantGarde Bk BT Book', 'AvantGarde Bk BT'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1165,
                  "y":115},
                "size":{
                  "width":23,
                  "height":34},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31134d963dd74589bcda8adc11aad79c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1159,
              "y":154},
            "size":{
              "width":323,
              "height":520}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"715bfcafbf8f4c6bb14b26f4fac7b814",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1159,
                  "y":154},
                "size":{
                  "width":323,
                  "height":520}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信首页-一_展示区/u14.png"}},
{
          "id":"0c7d958b43e74d9f8c359c062e77e458",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1188,
              "y":113},
            "size":{
              "width":41,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1307864f77a14bb591457317b71f705c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1188,
                  "y":113},
                "size":{
                  "width":41,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信首页-一_展示区/u26.png"}},
{
          "id":"b15c707a6b93476d814291b66eff6fb9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1158,
              "y":154},
            "size":{
              "width":327,
              "height":38},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f8fb183f3ce447592c9711bd17e3761",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1158,
                  "y":154},
                "size":{
                  "width":327,
                  "height":38},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一手房-新盘速递/u17.png"}},
{
          "id":"cf938dec0b1144848017f1fb05bc19dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":1250,
              "y":162},
            "size":{
              "width":173,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"315b65f43f34462ebf27f5f097f72556",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":1250,
                  "y":162},
                "size":{
                  "width":173,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"602e7852751544bc8518828cb04fc2c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1163,
              "y":229},
            "size":{
              "width":317,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0df249f624ff424991412bf8ebf0f355",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1163,
                  "y":229},
                "size":{
                  "width":317,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一手房-直播间/u18.png"}},
{
          "id":"f0991795af1049ccad9b4c7f943f0523",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1156,
              "y":184},
            "size":{
              "width":331,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新房速递-详情/u90_line.png"}},
{
          "id":"954d99a8478c4985af369bfaff116abc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1230,
              "y":233},
            "size":{
              "width":137,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f130ae1ac21744bf96f1e08b7f7863df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1230,
                  "y":233},
                "size":{
                  "width":137,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2832983aeb6b46938b9716711a18d4ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC99},
            "location":{
              "x":1156,
              "y":640},
            "size":{
              "width":164,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5849d816e9ed4a2f834e4232a68892b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC99},
                "location":{
                  "x":1156,
                  "y":640},
                "size":{
                  "width":164,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一手房-直播间/u21.png"}},
{
          "id":"741d54935a8c45a781786714bc5c01ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF006699},
            "location":{
              "x":1320,
              "y":640},
            "size":{
              "width":163,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b322f42f26074ed7a544abb47dc5256b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF006699},
                "location":{
                  "x":1320,
                  "y":640},
                "size":{
                  "width":163,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一手房-直播间/u23.png"}},
{
          "id":"c5c038601ea84a7293057e2592b08913",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1180,
              "y":233},
            "size":{
              "width":162,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7904b20b0b1d40d98d2989ab9fb6838e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1180,
                  "y":233},
                "size":{
                  "width":162,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98db05cd62d7416cb50976cfacf65195",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1164,
              "y":270},
            "size":{
              "width":317,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7468408819f446b987d5b487a9d53b03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1164,
                  "y":270},
                "size":{
                  "width":317,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一手房-直播间/u18.png"}},
{
          "id":"2f6305e47d2944f08e81b96d67525b8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1180,
              "y":274},
            "size":{
              "width":162,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbed405b15214b9789f92576835142d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1180,
                  "y":274},
                "size":{
                  "width":162,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aaff2f18714240a3b69b9b5542402891",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1242,
              "y":274},
            "size":{
              "width":162,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f371c7cf0c04d71880ca8cbc8c5604e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1242,
                  "y":274},
                "size":{
                  "width":162,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"288d4d99f37a4d87adb0281882436bb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1164,
              "y":316},
            "size":{
              "width":317,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b09fc85e6ff47b9a7723a3c85ce6be0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1164,
                  "y":316},
                "size":{
                  "width":317,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一手房-直播间/u18.png"}},
{
          "id":"c61a6a4e06da4d47aa13d0fdd15dc468",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1242,
              "y":320},
            "size":{
              "width":162,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee110b670ff84770bb54f85415574f38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1242,
                  "y":320},
                "size":{
                  "width":162,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"350abce3044e4d2cb980a0dcf6ea8449",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1180,
              "y":320},
            "size":{
              "width":162,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e12f53fb3c274a729a18e6fd18bf0b35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1180,
                  "y":320},
                "size":{
                  "width":162,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9955eb0d13ec472a9a7cc4e06cd7be08",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":423,
              "y":640},
            "size":{
              "width":35,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10aa57d8c26048a587b4f095e637ee36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":423,
                  "y":640},
                "size":{
                  "width":35,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一手房-直播间/u76.png"}},
{
          "id":"fa7f645924d54a919190d6f32490e3bc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1437,
              "y":640},
            "size":{
              "width":35,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79d7507af8164fd8ab358aa0ddbe5ac3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1437,
                  "y":640},
                "size":{
                  "width":35,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一手房-直播间/u76.png"}},
{
          "id":"dea932a51dfb4a04ba6765fbd659b61d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":863,
              "y":123},
            "size":{
              "width":81,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc840bb6c1314eed98664ac406de07a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":863,
                  "y":123},
                "size":{
                  "width":81,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a3c9b3b3978497ea5af46bddd9a6c91",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'AvantGarde Bk BT Book', 'AvantGarde Bk BT'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":756,
              "y":114},
            "size":{
              "width":23,
              "height":34},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af3af1ab3f5f4181b64062e8fc53456d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'AvantGarde Bk BT Book', 'AvantGarde Bk BT'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":756,
                  "y":114},
                "size":{
                  "width":23,
                  "height":34},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f14116a5ff840a3a6a8eeeeb7360282",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":704,
              "y":10},
            "size":{
              "width":405,
              "height":776},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29f4d18834d2442892abe8832ab119db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":704,
                  "y":10},
                "size":{
                  "width":405,
                  "height":776},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信首页-一_展示区/u8.png"}},
{
          "id":"5184c7172c574721aae0f9df17ad36d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":814,
              "y":123},
            "size":{
              "width":100,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f922ba51a2a482e8dd19fb72a0902c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":814,
                  "y":123},
                "size":{
                  "width":100,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ff2c8869a1d49b88fa6d637dd0f4031",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'AvantGarde Bk BT Book', 'AvantGarde Bk BT'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":749,
              "y":114},
            "size":{
              "width":23,
              "height":34},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"074e56ea69f645ed855bf89134a33652",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'AvantGarde Bk BT Book', 'AvantGarde Bk BT'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":749,
                  "y":114},
                "size":{
                  "width":23,
                  "height":34},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f1aff8b770a2483db10f350bfe2249cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":743,
              "y":153},
            "size":{
              "width":323,
              "height":520}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba064d2e88d04c43857842c0d3ef379b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":743,
                  "y":153},
                "size":{
                  "width":323,
                  "height":520}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信首页-一_展示区/u14.png"}},
{
          "id":"53e829082590494e9bdbeddc5d031bb3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":772,
              "y":112},
            "size":{
              "width":41,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a10633999d714dc9aa136ed38d9881cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":772,
                  "y":112},
                "size":{
                  "width":41,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信首页-一_展示区/u26.png"}},
{
          "id":"631bb35c1bf34a8fbf8df933746424a1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":742,
              "y":153},
            "size":{
              "width":327,
              "height":38},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b87013c9f1147f79896f5405e9f3852",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":742,
                  "y":153},
                "size":{
                  "width":327,
                  "height":38},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一手房-新盘速递/u17.png"}},
{
          "id":"9d1f86e058024a21a156618963bba4ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":834,
              "y":161},
            "size":{
              "width":173,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6c07ff3dc8c4c37866691fc92436ea1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":834,
                  "y":161},
                "size":{
                  "width":173,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56a6c045145c4a96b395d3c551a8a710",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":747,
              "y":228},
            "size":{
              "width":317,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df3caea07e104cf28c78ddb69886b43c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":747,
                  "y":228},
                "size":{
                  "width":317,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一手房-直播间/u18.png"}},
{
          "id":"dcfcb88c0f8d46a6b282561e80b49c74",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":183},
            "size":{
              "width":331,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新房速递-详情/u90_line.png"}},
{
          "id":"390a78b89cdf4c09826565ff72bee257",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC99},
            "location":{
              "x":740,
              "y":639},
            "size":{
              "width":164,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fe9e4120ca946dc9ce307b66d9eb70f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC99},
                "location":{
                  "x":740,
                  "y":639},
                "size":{
                  "width":164,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一手房-直播间/u21.png"}},
{
          "id":"417acd150748440c8efd4ca7357b6971",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF006699},
            "location":{
              "x":904,
              "y":639},
            "size":{
              "width":163,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0cf3b51b0ad4364909ed63a88344259",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF006699},
                "location":{
                  "x":904,
                  "y":639},
                "size":{
                  "width":163,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一手房-直播间/u23.png"}},
{
          "id":"973fc4201b5d4e2db3d1a6296895a0c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":762,
              "y":232},
            "size":{
              "width":162,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d2446fdc4cd4e5fb827a1be707dd2f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":762,
                  "y":232},
                "size":{
                  "width":162,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e34be3c21494525bf76e43940e831e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":748,
              "y":269},
            "size":{
              "width":317,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7f2bec6a0b642e6ab43517d7e88a830",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":748,
                  "y":269},
                "size":{
                  "width":317,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一手房-直播间/u18.png"}},
{
          "id":"b877bae5d6b44a7ab9a408efd15ac85a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":764,
              "y":273},
            "size":{
              "width":162,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4440abc381184211a4a61bf0a76d3415",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":764,
                  "y":273},
                "size":{
                  "width":162,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7adcb5de1d5247d199d80b1223cc61c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":748,
              "y":315},
            "size":{
              "width":317,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdae7ec517814c0fbc85028689d67c72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":748,
                  "y":315},
                "size":{
                  "width":317,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一手房-直播间/u18.png"}},
{
          "id":"63353c88a77941e9a24789d855e023d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":764,
              "y":319},
            "size":{
              "width":162,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e08a22d56d74074825e26b6df285dab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":764,
                  "y":319},
                "size":{
                  "width":162,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"320bc07125f5485195d7738070000630",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":859,
              "y":639},
            "size":{
              "width":35,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e850139a2054ea098b56bd3e23e962b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":859,
                  "y":639},
                "size":{
                  "width":35,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/一手房-直播间/u76.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "1c3f81d6865f43e48ac5ade288f16fb8":{
      "scriptId":"u0"},
    "29c094fc46204abab5cb8184c7b39fca":{
      "scriptId":"u1"},
    "0b445b7b985c4a939d313f3741010f83":{
      "scriptId":"u2"},
    "4a883d74d6974d39850dc74fb39b8af4":{
      "scriptId":"u3"},
    "54e55945f053472b8f6732116a041f40":{
      "scriptId":"u4"},
    "4d4954d9f9224400be1f1be67c190818":{
      "scriptId":"u5"},
    "fcbd10169d7c4e50a8ba773f2cb0593d":{
      "scriptId":"u6"},
    "b38f3bb815f646b78e810f984edf3eb2":{
      "scriptId":"u7"},
    "f413d0a71537470688815ac3dc84e71c":{
      "scriptId":"u8"},
    "ad0df6cde9224f259dea8ac89206945f":{
      "scriptId":"u9"},
    "99922959858b4455afa91d8c1e4b0259":{
      "scriptId":"u10"},
    "7b897702d3824097a5048cd4753a4165":{
      "scriptId":"u11"},
    "a90ba30c39cb450ca3b5e4830f411875":{
      "scriptId":"u12"},
    "fe8eb8fd60e64765b24ce9dc2c5a3118":{
      "scriptId":"u13"},
    "831d34d344f34999ab1dd47b0e3a99bc":{
      "scriptId":"u14"},
    "2ccc262cd7254129924cca15ffde3f43":{
      "scriptId":"u15"},
    "096b0138e26d4c29b3cd90136a896e29":{
      "scriptId":"u16"},
    "f92c8c5576c04739ad4545681f665c93":{
      "scriptId":"u17"},
    "932781e5825c4eb09d411a73bff588d9":{
      "scriptId":"u18"},
    "43e5d5610fba4e2b929be872b4a83c9e":{
      "scriptId":"u19"},
    "6405ab3590cd4fb7a83c983cdf391b6f":{
      "scriptId":"u20"},
    "a70b7c0ca05248cfa78e39063d1d4cc2":{
      "scriptId":"u21"},
    "15b7ebad01b848cdbbaf1eed2897cd6b":{
      "scriptId":"u22"},
    "12e1f761fa7149549fd6c1522d26e795":{
      "scriptId":"u23"},
    "823826bc41a84e0a9897ea443f1e9499":{
      "scriptId":"u24"},
    "ec31e9da68904657b04db5ae6ca8f62f":{
      "scriptId":"u25"},
    "6334e22844b44442b281195aa7a9bb86":{
      "scriptId":"u26"},
    "ed872e0e6f00422881c79966f5b9f401":{
      "scriptId":"u27"},
    "d2a300923d824eefb43321f818acee51":{
      "scriptId":"u28"},
    "62a4708829834bba86a14e5649a61016":{
      "scriptId":"u29"},
    "6ce599d2f0d54177a801551a67595ccd":{
      "scriptId":"u30"},
    "80d8f43f67104b5083e737569acf1e05":{
      "scriptId":"u31"},
    "d62ca94627074bb2a068e14f106cbc69":{
      "scriptId":"u32"},
    "ae3456cb622a404b969ff3471f857765":{
      "scriptId":"u33"},
    "e5bf5096575b427bab6ea09bdde8382f":{
      "scriptId":"u34"},
    "f4eb042b98b8434abd1dcd354a555480":{
      "scriptId":"u35"},
    "3b48ae252a1f482390e5cf1858f084da":{
      "scriptId":"u36"},
    "5cdb023fe40b488c99b74be445778057":{
      "scriptId":"u37"},
    "67785ed0351647c28b418ea91fb0c819":{
      "scriptId":"u38"},
    "24cef320858945148eb5a0fc27c9d0d1":{
      "scriptId":"u39"},
    "542dec13409a4c058b4f662d863ac640":{
      "scriptId":"u40"},
    "68a43a067f0f46e9aeb69cbf0f3cfba0":{
      "scriptId":"u41"},
    "603cae258fc64fbb939f08bcbcaa01a3":{
      "scriptId":"u42"},
    "15398f385188449fb93d45897574110d":{
      "scriptId":"u43"},
    "4e5536d7495640238f216676bf82d40f":{
      "scriptId":"u44"},
    "31134d963dd74589bcda8adc11aad79c":{
      "scriptId":"u45"},
    "715bfcafbf8f4c6bb14b26f4fac7b814":{
      "scriptId":"u46"},
    "0c7d958b43e74d9f8c359c062e77e458":{
      "scriptId":"u47"},
    "1307864f77a14bb591457317b71f705c":{
      "scriptId":"u48"},
    "b15c707a6b93476d814291b66eff6fb9":{
      "scriptId":"u49"},
    "5f8fb183f3ce447592c9711bd17e3761":{
      "scriptId":"u50"},
    "cf938dec0b1144848017f1fb05bc19dc":{
      "scriptId":"u51"},
    "315b65f43f34462ebf27f5f097f72556":{
      "scriptId":"u52"},
    "602e7852751544bc8518828cb04fc2c8":{
      "scriptId":"u53"},
    "0df249f624ff424991412bf8ebf0f355":{
      "scriptId":"u54"},
    "f0991795af1049ccad9b4c7f943f0523":{
      "scriptId":"u55"},
    "954d99a8478c4985af369bfaff116abc":{
      "scriptId":"u56"},
    "f130ae1ac21744bf96f1e08b7f7863df":{
      "scriptId":"u57"},
    "2832983aeb6b46938b9716711a18d4ca":{
      "scriptId":"u58"},
    "5849d816e9ed4a2f834e4232a68892b9":{
      "scriptId":"u59"},
    "741d54935a8c45a781786714bc5c01ff":{
      "scriptId":"u60"},
    "b322f42f26074ed7a544abb47dc5256b":{
      "scriptId":"u61"},
    "c5c038601ea84a7293057e2592b08913":{
      "scriptId":"u62"},
    "7904b20b0b1d40d98d2989ab9fb6838e":{
      "scriptId":"u63"},
    "98db05cd62d7416cb50976cfacf65195":{
      "scriptId":"u64"},
    "7468408819f446b987d5b487a9d53b03":{
      "scriptId":"u65"},
    "2f6305e47d2944f08e81b96d67525b8c":{
      "scriptId":"u66"},
    "bbed405b15214b9789f92576835142d2":{
      "scriptId":"u67"},
    "aaff2f18714240a3b69b9b5542402891":{
      "scriptId":"u68"},
    "3f371c7cf0c04d71880ca8cbc8c5604e":{
      "scriptId":"u69"},
    "288d4d99f37a4d87adb0281882436bb4":{
      "scriptId":"u70"},
    "8b09fc85e6ff47b9a7723a3c85ce6be0":{
      "scriptId":"u71"},
    "c61a6a4e06da4d47aa13d0fdd15dc468":{
      "scriptId":"u72"},
    "ee110b670ff84770bb54f85415574f38":{
      "scriptId":"u73"},
    "350abce3044e4d2cb980a0dcf6ea8449":{
      "scriptId":"u74"},
    "e12f53fb3c274a729a18e6fd18bf0b35":{
      "scriptId":"u75"},
    "9955eb0d13ec472a9a7cc4e06cd7be08":{
      "scriptId":"u76"},
    "10aa57d8c26048a587b4f095e637ee36":{
      "scriptId":"u77"},
    "fa7f645924d54a919190d6f32490e3bc":{
      "scriptId":"u78"},
    "79d7507af8164fd8ab358aa0ddbe5ac3":{
      "scriptId":"u79"},
    "dea932a51dfb4a04ba6765fbd659b61d":{
      "scriptId":"u80"},
    "cc840bb6c1314eed98664ac406de07a3":{
      "scriptId":"u81"},
    "5a3c9b3b3978497ea5af46bddd9a6c91":{
      "scriptId":"u82"},
    "af3af1ab3f5f4181b64062e8fc53456d":{
      "scriptId":"u83"},
    "6f14116a5ff840a3a6a8eeeeb7360282":{
      "scriptId":"u84"},
    "29f4d18834d2442892abe8832ab119db":{
      "scriptId":"u85"},
    "5184c7172c574721aae0f9df17ad36d7":{
      "scriptId":"u86"},
    "8f922ba51a2a482e8dd19fb72a0902c5":{
      "scriptId":"u87"},
    "2ff2c8869a1d49b88fa6d637dd0f4031":{
      "scriptId":"u88"},
    "074e56ea69f645ed855bf89134a33652":{
      "scriptId":"u89"},
    "f1aff8b770a2483db10f350bfe2249cf":{
      "scriptId":"u90"},
    "ba064d2e88d04c43857842c0d3ef379b":{
      "scriptId":"u91"},
    "53e829082590494e9bdbeddc5d031bb3":{
      "scriptId":"u92"},
    "a10633999d714dc9aa136ed38d9881cd":{
      "scriptId":"u93"},
    "631bb35c1bf34a8fbf8df933746424a1":{
      "scriptId":"u94"},
    "4b87013c9f1147f79896f5405e9f3852":{
      "scriptId":"u95"},
    "9d1f86e058024a21a156618963bba4ee":{
      "scriptId":"u96"},
    "b6c07ff3dc8c4c37866691fc92436ea1":{
      "scriptId":"u97"},
    "56a6c045145c4a96b395d3c551a8a710":{
      "scriptId":"u98"},
    "df3caea07e104cf28c78ddb69886b43c":{
      "scriptId":"u99"},
    "dcfcb88c0f8d46a6b282561e80b49c74":{
      "scriptId":"u100"},
    "390a78b89cdf4c09826565ff72bee257":{
      "scriptId":"u101"},
    "2fe9e4120ca946dc9ce307b66d9eb70f":{
      "scriptId":"u102"},
    "417acd150748440c8efd4ca7357b6971":{
      "scriptId":"u103"},
    "e0cf3b51b0ad4364909ed63a88344259":{
      "scriptId":"u104"},
    "973fc4201b5d4e2db3d1a6296895a0c4":{
      "scriptId":"u105"},
    "4d2446fdc4cd4e5fb827a1be707dd2f3":{
      "scriptId":"u106"},
    "7e34be3c21494525bf76e43940e831e8":{
      "scriptId":"u107"},
    "e7f2bec6a0b642e6ab43517d7e88a830":{
      "scriptId":"u108"},
    "b877bae5d6b44a7ab9a408efd15ac85a":{
      "scriptId":"u109"},
    "4440abc381184211a4a61bf0a76d3415":{
      "scriptId":"u110"},
    "7adcb5de1d5247d199d80b1223cc61c0":{
      "scriptId":"u111"},
    "cdae7ec517814c0fbc85028689d67c72":{
      "scriptId":"u112"},
    "63353c88a77941e9a24789d855e023d3":{
      "scriptId":"u113"},
    "5e08a22d56d74074825e26b6df285dab":{
      "scriptId":"u114"},
    "320bc07125f5485195d7738070000630":{
      "scriptId":"u115"},
    "6e850139a2054ea098b56bd3e23e962b":{
      "scriptId":"u116"}}});